# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cppad_found <- function() {
    invisible(.Call('FLasher_cppad_found', PACKAGE = 'FLasher'))
}

poly <- function(k_in, x_in) {
    .Call('FLasher_poly', PACKAGE = 'FLasher', k_in, x_in)
}

rcpp_hello_world <- function() {
    .Call('FLasher_rcpp_hello_world', PACKAGE = 'FLasher')
}

