# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_dataframe_year <- function(ctrl) {
    .Call('FLasher_get_dataframe_year', PACKAGE = 'FLasher', ctrl)
}

get_dataframe_value <- function(ctrl) {
    .Call('FLasher_get_dataframe_value', PACKAGE = 'FLasher', ctrl)
}

get_dataframe_quantity <- function(ctrl) {
    .Call('FLasher_get_dataframe_quantity', PACKAGE = 'FLasher', ctrl)
}

cppad_found <- function() {
    invisible(.Call('FLasher_cppad_found', PACKAGE = 'FLasher'))
}

poly <- function(k_in, x_in) {
    .Call('FLasher_poly', PACKAGE = 'FLasher', k_in, x_in)
}

rcpp_hello_world <- function() {
    .Call('FLasher_rcpp_hello_world', PACKAGE = 'FLasher')
}

test_FLQuant_FLQuant_multiplier_assignment_operator <- function(flq1, flq2) {
    .Call('FLasher_test_FLQuant_FLQuant_multiplier_assignment_operator', PACKAGE = 'FLasher', flq1, flq2)
}

test_FLQuantAD_FLQuant_multiplier_assignment_operator <- function(flqad1, flq2) {
    .Call('FLasher_test_FLQuantAD_FLQuant_multiplier_assignment_operator', PACKAGE = 'FLasher', flqad1, flq2)
}

test_FLQuantAD_FLQuantAD_multiplier_assignment_operator <- function(flqad1, flqad2) {
    .Call('FLasher_test_FLQuantAD_FLQuantAD_multiplier_assignment_operator', PACKAGE = 'FLasher', flqad1, flqad2)
}

test_FLQuant_double_multiplier_assignment_operator <- function(flq1, value) {
    .Call('FLasher_test_FLQuant_double_multiplier_assignment_operator', PACKAGE = 'FLasher', flq1, value)
}

test_FLQuantAD_double_multiplier_assignment_operator <- function(flqad1, value) {
    .Call('FLasher_test_FLQuantAD_double_multiplier_assignment_operator', PACKAGE = 'FLasher', flqad1, value)
}

test_FLQuantAD_adouble_multiplier_assignment_operator <- function(flqad1, value) {
    .Call('FLasher_test_FLQuantAD_adouble_multiplier_assignment_operator', PACKAGE = 'FLasher', flqad1, value)
}

test_FLQuant_FLQuant_multiplier_operator <- function(flq1, flq2) {
    .Call('FLasher_test_FLQuant_FLQuant_multiplier_operator', PACKAGE = 'FLasher', flq1, flq2)
}

test_FLQuantAD_FLQuant_multiplier_operator <- function(flqad1, flq2) {
    .Call('FLasher_test_FLQuantAD_FLQuant_multiplier_operator', PACKAGE = 'FLasher', flqad1, flq2)
}

test_FLQuant_FLQuantAD_multiplier_operator <- function(flq1, flqad2) {
    .Call('FLasher_test_FLQuant_FLQuantAD_multiplier_operator', PACKAGE = 'FLasher', flq1, flqad2)
}

test_FLQuantAD_FLQuantAD_multiplier_operator <- function(flqad1, flqad2) {
    .Call('FLasher_test_FLQuantAD_FLQuantAD_multiplier_operator', PACKAGE = 'FLasher', flqad1, flqad2)
}

test_FLQuant_double_multiplier_operator <- function(flq1, value) {
    .Call('FLasher_test_FLQuant_double_multiplier_operator', PACKAGE = 'FLasher', flq1, value)
}

test_double_FLQuant_multiplier_operator <- function(value, flq1) {
    .Call('FLasher_test_double_FLQuant_multiplier_operator', PACKAGE = 'FLasher', value, flq1)
}

test_double_FLQuantAD_multiplier_operator <- function(value, flq1) {
    .Call('FLasher_test_double_FLQuantAD_multiplier_operator', PACKAGE = 'FLasher', value, flq1)
}

test_FLQuantAD_double_multiplier_operator <- function(flq1, value) {
    .Call('FLasher_test_FLQuantAD_double_multiplier_operator', PACKAGE = 'FLasher', flq1, value)
}

test_FLQuant_adouble_multiplier_operator <- function(flq1, value) {
    .Call('FLasher_test_FLQuant_adouble_multiplier_operator', PACKAGE = 'FLasher', flq1, value)
}

test_adouble_FLQuant_multiplier_operator <- function(value, flq1) {
    .Call('FLasher_test_adouble_FLQuant_multiplier_operator', PACKAGE = 'FLasher', value, flq1)
}

test_FLQuantAD_adouble_multiplier_operator <- function(flq1, value) {
    .Call('FLasher_test_FLQuantAD_adouble_multiplier_operator', PACKAGE = 'FLasher', flq1, value)
}

test_adouble_FLQuantAD_multiplier_operator <- function(value, flq1) {
    .Call('FLasher_test_adouble_FLQuantAD_multiplier_operator', PACKAGE = 'FLasher', value, flq1)
}

test_FLQuant_FLQuant_division_assignment_operator <- function(flq1, flq2) {
    .Call('FLasher_test_FLQuant_FLQuant_division_assignment_operator', PACKAGE = 'FLasher', flq1, flq2)
}

test_FLQuantAD_FLQuant_division_assignment_operator <- function(flqad1, flq2) {
    .Call('FLasher_test_FLQuantAD_FLQuant_division_assignment_operator', PACKAGE = 'FLasher', flqad1, flq2)
}

test_FLQuantAD_FLQuantAD_division_assignment_operator <- function(flqad1, flqad2) {
    .Call('FLasher_test_FLQuantAD_FLQuantAD_division_assignment_operator', PACKAGE = 'FLasher', flqad1, flqad2)
}

test_FLQuant_double_division_assignment_operator <- function(flq1, value) {
    .Call('FLasher_test_FLQuant_double_division_assignment_operator', PACKAGE = 'FLasher', flq1, value)
}

test_FLQuantAD_double_division_assignment_operator <- function(flqad1, value) {
    .Call('FLasher_test_FLQuantAD_double_division_assignment_operator', PACKAGE = 'FLasher', flqad1, value)
}

test_FLQuantAD_adouble_division_assignment_operator <- function(flqad1, value) {
    .Call('FLasher_test_FLQuantAD_adouble_division_assignment_operator', PACKAGE = 'FLasher', flqad1, value)
}

test_FLQuant_FLQuant_division_operator <- function(flq1, flq2) {
    .Call('FLasher_test_FLQuant_FLQuant_division_operator', PACKAGE = 'FLasher', flq1, flq2)
}

test_FLQuantAD_FLQuant_division_operator <- function(flqad1, flq2) {
    .Call('FLasher_test_FLQuantAD_FLQuant_division_operator', PACKAGE = 'FLasher', flqad1, flq2)
}

test_FLQuant_FLQuantAD_division_operator <- function(flq1, flqad2) {
    .Call('FLasher_test_FLQuant_FLQuantAD_division_operator', PACKAGE = 'FLasher', flq1, flqad2)
}

test_FLQuantAD_FLQuantAD_division_operator <- function(flqad1, flqad2) {
    .Call('FLasher_test_FLQuantAD_FLQuantAD_division_operator', PACKAGE = 'FLasher', flqad1, flqad2)
}

test_FLQuant_double_division_operator <- function(flq1, value) {
    .Call('FLasher_test_FLQuant_double_division_operator', PACKAGE = 'FLasher', flq1, value)
}

test_double_FLQuant_division_operator <- function(value, flq1) {
    .Call('FLasher_test_double_FLQuant_division_operator', PACKAGE = 'FLasher', value, flq1)
}

test_double_FLQuantAD_division_operator <- function(value, flq1) {
    .Call('FLasher_test_double_FLQuantAD_division_operator', PACKAGE = 'FLasher', value, flq1)
}

test_FLQuantAD_double_division_operator <- function(flq1, value) {
    .Call('FLasher_test_FLQuantAD_double_division_operator', PACKAGE = 'FLasher', flq1, value)
}

test_FLQuant_adouble_division_operator <- function(flq1, value) {
    .Call('FLasher_test_FLQuant_adouble_division_operator', PACKAGE = 'FLasher', flq1, value)
}

test_adouble_FLQuant_division_operator <- function(value, flq1) {
    .Call('FLasher_test_adouble_FLQuant_division_operator', PACKAGE = 'FLasher', value, flq1)
}

test_FLQuantAD_adouble_division_operator <- function(flq1, value) {
    .Call('FLasher_test_FLQuantAD_adouble_division_operator', PACKAGE = 'FLasher', flq1, value)
}

test_adouble_FLQuantAD_division_operator <- function(value, flq1) {
    .Call('FLasher_test_adouble_FLQuantAD_division_operator', PACKAGE = 'FLasher', value, flq1)
}

test_FLQuant_FLQuant_subtraction_assignment_operator <- function(flq1, flq2) {
    .Call('FLasher_test_FLQuant_FLQuant_subtraction_assignment_operator', PACKAGE = 'FLasher', flq1, flq2)
}

test_FLQuantAD_FLQuant_subtraction_assignment_operator <- function(flqad1, flq2) {
    .Call('FLasher_test_FLQuantAD_FLQuant_subtraction_assignment_operator', PACKAGE = 'FLasher', flqad1, flq2)
}

test_FLQuantAD_FLQuantAD_subtraction_assignment_operator <- function(flqad1, flqad2) {
    .Call('FLasher_test_FLQuantAD_FLQuantAD_subtraction_assignment_operator', PACKAGE = 'FLasher', flqad1, flqad2)
}

test_FLQuant_double_subtraction_assignment_operator <- function(flq1, value) {
    .Call('FLasher_test_FLQuant_double_subtraction_assignment_operator', PACKAGE = 'FLasher', flq1, value)
}

test_FLQuantAD_double_subtraction_assignment_operator <- function(flqad1, value) {
    .Call('FLasher_test_FLQuantAD_double_subtraction_assignment_operator', PACKAGE = 'FLasher', flqad1, value)
}

test_FLQuantAD_adouble_subtraction_assignment_operator <- function(flqad1, value) {
    .Call('FLasher_test_FLQuantAD_adouble_subtraction_assignment_operator', PACKAGE = 'FLasher', flqad1, value)
}

test_FLQuant_FLQuant_subtraction_operator <- function(flq1, flq2) {
    .Call('FLasher_test_FLQuant_FLQuant_subtraction_operator', PACKAGE = 'FLasher', flq1, flq2)
}

test_FLQuantAD_FLQuant_subtraction_operator <- function(flqad1, flq2) {
    .Call('FLasher_test_FLQuantAD_FLQuant_subtraction_operator', PACKAGE = 'FLasher', flqad1, flq2)
}

test_FLQuant_FLQuantAD_subtraction_operator <- function(flq1, flqad2) {
    .Call('FLasher_test_FLQuant_FLQuantAD_subtraction_operator', PACKAGE = 'FLasher', flq1, flqad2)
}

test_FLQuantAD_FLQuantAD_subtraction_operator <- function(flqad1, flqad2) {
    .Call('FLasher_test_FLQuantAD_FLQuantAD_subtraction_operator', PACKAGE = 'FLasher', flqad1, flqad2)
}

test_FLQuant_double_subtraction_operator <- function(flq1, value) {
    .Call('FLasher_test_FLQuant_double_subtraction_operator', PACKAGE = 'FLasher', flq1, value)
}

test_double_FLQuant_subtraction_operator <- function(value, flq1) {
    .Call('FLasher_test_double_FLQuant_subtraction_operator', PACKAGE = 'FLasher', value, flq1)
}

test_double_FLQuantAD_subtraction_operator <- function(value, flq1) {
    .Call('FLasher_test_double_FLQuantAD_subtraction_operator', PACKAGE = 'FLasher', value, flq1)
}

test_FLQuantAD_double_subtraction_operator <- function(flq1, value) {
    .Call('FLasher_test_FLQuantAD_double_subtraction_operator', PACKAGE = 'FLasher', flq1, value)
}

test_FLQuant_adouble_subtraction_operator <- function(flq1, value) {
    .Call('FLasher_test_FLQuant_adouble_subtraction_operator', PACKAGE = 'FLasher', flq1, value)
}

test_adouble_FLQuant_subtraction_operator <- function(value, flq1) {
    .Call('FLasher_test_adouble_FLQuant_subtraction_operator', PACKAGE = 'FLasher', value, flq1)
}

test_FLQuantAD_adouble_subtraction_operator <- function(flq1, value) {
    .Call('FLasher_test_FLQuantAD_adouble_subtraction_operator', PACKAGE = 'FLasher', flq1, value)
}

test_adouble_FLQuantAD_subtraction_operator <- function(value, flq1) {
    .Call('FLasher_test_adouble_FLQuantAD_subtraction_operator', PACKAGE = 'FLasher', value, flq1)
}

test_FLQuant_FLQuant_addition_assignment_operator <- function(flq1, flq2) {
    .Call('FLasher_test_FLQuant_FLQuant_addition_assignment_operator', PACKAGE = 'FLasher', flq1, flq2)
}

test_FLQuantAD_FLQuant_addition_assignment_operator <- function(flqad1, flq2) {
    .Call('FLasher_test_FLQuantAD_FLQuant_addition_assignment_operator', PACKAGE = 'FLasher', flqad1, flq2)
}

test_FLQuantAD_FLQuantAD_addition_assignment_operator <- function(flqad1, flqad2) {
    .Call('FLasher_test_FLQuantAD_FLQuantAD_addition_assignment_operator', PACKAGE = 'FLasher', flqad1, flqad2)
}

test_FLQuant_double_addition_assignment_operator <- function(flq1, value) {
    .Call('FLasher_test_FLQuant_double_addition_assignment_operator', PACKAGE = 'FLasher', flq1, value)
}

test_FLQuantAD_double_addition_assignment_operator <- function(flqad1, value) {
    .Call('FLasher_test_FLQuantAD_double_addition_assignment_operator', PACKAGE = 'FLasher', flqad1, value)
}

test_FLQuantAD_adouble_addition_assignment_operator <- function(flqad1, value) {
    .Call('FLasher_test_FLQuantAD_adouble_addition_assignment_operator', PACKAGE = 'FLasher', flqad1, value)
}

test_FLQuant_FLQuant_addition_operator <- function(flq1, flq2) {
    .Call('FLasher_test_FLQuant_FLQuant_addition_operator', PACKAGE = 'FLasher', flq1, flq2)
}

test_FLQuantAD_FLQuant_addition_operator <- function(flqad1, flq2) {
    .Call('FLasher_test_FLQuantAD_FLQuant_addition_operator', PACKAGE = 'FLasher', flqad1, flq2)
}

test_FLQuant_FLQuantAD_addition_operator <- function(flq1, flqad2) {
    .Call('FLasher_test_FLQuant_FLQuantAD_addition_operator', PACKAGE = 'FLasher', flq1, flqad2)
}

test_FLQuantAD_FLQuantAD_addition_operator <- function(flqad1, flqad2) {
    .Call('FLasher_test_FLQuantAD_FLQuantAD_addition_operator', PACKAGE = 'FLasher', flqad1, flqad2)
}

test_FLQuant_double_addition_operator <- function(flq1, value) {
    .Call('FLasher_test_FLQuant_double_addition_operator', PACKAGE = 'FLasher', flq1, value)
}

test_double_FLQuant_addition_operator <- function(value, flq1) {
    .Call('FLasher_test_double_FLQuant_addition_operator', PACKAGE = 'FLasher', value, flq1)
}

test_double_FLQuantAD_addition_operator <- function(value, flq1) {
    .Call('FLasher_test_double_FLQuantAD_addition_operator', PACKAGE = 'FLasher', value, flq1)
}

test_FLQuantAD_double_addition_operator <- function(flq1, value) {
    .Call('FLasher_test_FLQuantAD_double_addition_operator', PACKAGE = 'FLasher', flq1, value)
}

test_FLQuant_adouble_addition_operator <- function(flq1, value) {
    .Call('FLasher_test_FLQuant_adouble_addition_operator', PACKAGE = 'FLasher', flq1, value)
}

test_adouble_FLQuant_addition_operator <- function(value, flq1) {
    .Call('FLasher_test_adouble_FLQuant_addition_operator', PACKAGE = 'FLasher', value, flq1)
}

test_FLQuantAD_adouble_addition_operator <- function(flq1, value) {
    .Call('FLasher_test_FLQuantAD_adouble_addition_operator', PACKAGE = 'FLasher', flq1, value)
}

test_adouble_FLQuantAD_addition_operator <- function(value, flq1) {
    .Call('FLasher_test_adouble_FLQuantAD_addition_operator', PACKAGE = 'FLasher', value, flq1)
}

test_FLQuant_log <- function(flq) {
    .Call('FLasher_test_FLQuant_log', PACKAGE = 'FLasher', flq)
}

test_FLQuantAD_log <- function(flq) {
    .Call('FLasher_test_FLQuantAD_log', PACKAGE = 'FLasher', flq)
}

test_FLQuant_exp <- function(flq) {
    .Call('FLasher_test_FLQuant_exp', PACKAGE = 'FLasher', flq)
}

test_FLQuantAD_exp <- function(flq) {
    .Call('FLasher_test_FLQuantAD_exp', PACKAGE = 'FLasher', flq)
}

test_composite_arithmetic_operators <- function(flqad, flq, value) {
    .Call('FLasher_test_composite_arithmetic_operators', PACKAGE = 'FLasher', flqad, flq, value)
}

test_FLQuant_quant_sum <- function(flq) {
    .Call('FLasher_test_FLQuant_quant_sum', PACKAGE = 'FLasher', flq)
}

test_FLQuantAD_quant_sum <- function(flq) {
    .Call('FLasher_test_FLQuantAD_quant_sum', PACKAGE = 'FLasher', flq)
}

test_FLQuant_quant_mean <- function(flq) {
    .Call('FLasher_test_FLQuant_quant_mean', PACKAGE = 'FLasher', flq)
}

test_FLQuantAD_quant_mean <- function(flq) {
    .Call('FLasher_test_FLQuantAD_quant_mean', PACKAGE = 'FLasher', flq)
}

test_FLQuant_max_quant <- function(flq) {
    .Call('FLasher_test_FLQuant_max_quant', PACKAGE = 'FLasher', flq)
}

test_FLQuantAD_max_quant <- function(flq) {
    .Call('FLasher_test_FLQuantAD_max_quant', PACKAGE = 'FLasher', flq)
}

test_FLQuant_scale_by_max_quant <- function(flq) {
    .Call('FLasher_test_FLQuant_scale_by_max_quant', PACKAGE = 'FLasher', flq)
}

test_FLQuantAD_scale_by_max_quant <- function(flq) {
    .Call('FLasher_test_FLQuantAD_scale_by_max_quant', PACKAGE = 'FLasher', flq)
}

test_simple_FLCatch_sexp_constructor <- function(flc_sexp) {
    .Call('FLasher_test_simple_FLCatch_sexp_constructor', PACKAGE = 'FLasher', flc_sexp)
}

test_FLCatch_sexp_constructor <- function(flc_sexp) {
    .Call('FLasher_test_FLCatch_sexp_constructor', PACKAGE = 'FLasher', flc_sexp)
}

test_FLCatchAD_sexp_constructor <- function(flc_sexp) {
    .Call('FLasher_test_FLCatchAD_sexp_constructor', PACKAGE = 'FLasher', flc_sexp)
}

test_FLCatch_as_wrap <- function(flc) {
    .Call('FLasher_test_FLCatch_as_wrap', PACKAGE = 'FLasher', flc)
}

test_FLCatchAD_as_wrap <- function(flc) {
    .Call('FLasher_test_FLCatchAD_as_wrap', PACKAGE = 'FLasher', flc)
}

test_FLCatch_copy_constructor <- function(flc1) {
    .Call('FLasher_test_FLCatch_copy_constructor', PACKAGE = 'FLasher', flc1)
}

test_FLCatchAD_copy_constructor <- function(flc1) {
    .Call('FLasher_test_FLCatchAD_copy_constructor', PACKAGE = 'FLasher', flc1)
}

test_FLCatch_copy_constructor2 <- function(flc1, quant, year, unit, season, area, iter, value) {
    .Call('FLasher_test_FLCatch_copy_constructor2', PACKAGE = 'FLasher', flc1, quant, year, unit, season, area, iter, value)
}

test_FLCatchAD_copy_constructor2 <- function(flc1, quant, year, unit, season, area, iter, value) {
    .Call('FLasher_test_FLCatchAD_copy_constructor2', PACKAGE = 'FLasher', flc1, quant, year, unit, season, area, iter, value)
}

test_FLCatch_assignment_operator <- function(flc1) {
    .Call('FLasher_test_FLCatch_assignment_operator', PACKAGE = 'FLasher', flc1)
}

test_FLCatchAD_assignment_operator <- function(flc1) {
    .Call('FLasher_test_FLCatchAD_assignment_operator', PACKAGE = 'FLasher', flc1)
}

test_FLCatch_assignment_operator2 <- function(flc1, quant, year, unit, season, area, iter, value) {
    .Call('FLasher_test_FLCatch_assignment_operator2', PACKAGE = 'FLasher', flc1, quant, year, unit, season, area, iter, value)
}

test_FLCatchAD_assignment_operator2 <- function(flc1, quant, year, unit, season, area, iter, value) {
    .Call('FLasher_test_FLCatchAD_assignment_operator2', PACKAGE = 'FLasher', flc1, quant, year, unit, season, area, iter, value)
}

test_FLCatch_const_get_accessors <- function(flc, quant, year, unit, season, area, iter) {
    .Call('FLasher_test_FLCatch_const_get_accessors', PACKAGE = 'FLasher', flc, quant, year, unit, season, area, iter)
}

test_FLCatchAD_const_get_accessors <- function(flc, quant, year, unit, season, area, iter) {
    .Call('FLasher_test_FLCatchAD_const_get_accessors', PACKAGE = 'FLasher', flc, quant, year, unit, season, area, iter)
}

test_FLCatch_get_accessors <- function(flc, quant, year, unit, season, area, iter) {
    .Call('FLasher_test_FLCatch_get_accessors', PACKAGE = 'FLasher', flc, quant, year, unit, season, area, iter)
}

test_FLCatchAD_get_accessors <- function(flc, quant, year, unit, season, area, iter) {
    .Call('FLasher_test_FLCatchAD_get_accessors', PACKAGE = 'FLasher', flc, quant, year, unit, season, area, iter)
}

test_FLCatch_set_accessors <- function(flc, quant, year, unit, season, area, iter, values) {
    .Call('FLasher_test_FLCatch_set_accessors', PACKAGE = 'FLasher', flc, quant, year, unit, season, area, iter, values)
}

test_FLCatchAD_set_accessors <- function(flc, quant, year, unit, season, area, iter, values) {
    .Call('FLasher_test_FLCatchAD_set_accessors', PACKAGE = 'FLasher', flc, quant, year, unit, season, area, iter, values)
}

test_FLCatch_landings <- function(flc) {
    .Call('FLasher_test_FLCatch_landings', PACKAGE = 'FLasher', flc)
}

test_FLCatchAD_landings <- function(flc) {
    .Call('FLasher_test_FLCatchAD_landings', PACKAGE = 'FLasher', flc)
}

test_FLCatch_discards <- function(flc) {
    .Call('FLasher_test_FLCatch_discards', PACKAGE = 'FLasher', flc)
}

test_FLCatchAD_discards <- function(flc) {
    .Call('FLasher_test_FLCatchAD_discards', PACKAGE = 'FLasher', flc)
}

test_FLCatch_catch_n <- function(flc) {
    .Call('FLasher_test_FLCatch_catch_n', PACKAGE = 'FLasher', flc)
}

test_FLCatchAD_catch_n <- function(flc) {
    .Call('FLasher_test_FLCatchAD_catch_n', PACKAGE = 'FLasher', flc)
}

test_FLCatch_catch_wt <- function(flc) {
    .Call('FLasher_test_FLCatch_catch_wt', PACKAGE = 'FLasher', flc)
}

test_FLCatchAD_catch_wt <- function(flc) {
    .Call('FLasher_test_FLCatchAD_catch_wt', PACKAGE = 'FLasher', flc)
}

test_FLCatch_catches <- function(flc) {
    .Call('FLasher_test_FLCatch_catches', PACKAGE = 'FLasher', flc)
}

test_FLCatchAD_catches <- function(flc) {
    .Call('FLasher_test_FLCatchAD_catches', PACKAGE = 'FLasher', flc)
}

test_FLCatch_discards_ratio <- function(flc) {
    .Call('FLasher_test_FLCatch_discards_ratio', PACKAGE = 'FLasher', flc)
}

test_FLCatchAD_discards_ratio <- function(flc) {
    .Call('FLasher_test_FLCatchAD_discards_ratio', PACKAGE = 'FLasher', flc)
}

test_FLCatch_landings_sel <- function(flc) {
    .Call('FLasher_test_FLCatch_landings_sel', PACKAGE = 'FLasher', flc)
}

test_FLCatchAD_landings_sel <- function(flc) {
    .Call('FLasher_test_FLCatchAD_landings_sel', PACKAGE = 'FLasher', flc)
}

test_FLCatch_discards_sel <- function(flc) {
    .Call('FLasher_test_FLCatch_discards_sel', PACKAGE = 'FLasher', flc)
}

test_FLCatchAD_discards_sel <- function(flc) {
    .Call('FLasher_test_FLCatchAD_discards_sel', PACKAGE = 'FLasher', flc)
}

test_FLCatchAD_catch_q_params <- function(flc, indices) {
    .Call('FLasher_test_FLCatchAD_catch_q_params', PACKAGE = 'FLasher', flc, indices)
}

test_FLCatchAD_catch_q_params_subset <- function(flc, indices_min, indices_max) {
    .Call('FLasher_test_FLCatchAD_catch_q_params_subset', PACKAGE = 'FLasher', flc, indices_min, indices_max)
}

test_FLCatches_as_wrap <- function(flcs) {
    .Call('FLasher_test_FLCatches_as_wrap', PACKAGE = 'FLasher', flcs)
}

test_FLCatches_sexp_constructor <- function(flcs_sexp1) {
    .Call('FLasher_test_FLCatches_sexp_constructor', PACKAGE = 'FLasher', flcs_sexp1)
}

test_FLCatches_FLCatch_constructor <- function(flc) {
    .Call('FLasher_test_FLCatches_FLCatch_constructor', PACKAGE = 'FLasher', flc)
}

test_FLCatches_copy_constructor <- function(flcs) {
    .Call('FLasher_test_FLCatches_copy_constructor', PACKAGE = 'FLasher', flcs)
}

test_FLCatches_copy_constructor2 <- function(flcs1, catches, quant, year, unit, season, area, iter, value) {
    .Call('FLasher_test_FLCatches_copy_constructor2', PACKAGE = 'FLasher', flcs1, catches, quant, year, unit, season, area, iter, value)
}

test_FLCatches_assignment_operator <- function(flcs) {
    .Call('FLasher_test_FLCatches_assignment_operator', PACKAGE = 'FLasher', flcs)
}

test_FLCatches_assignment_operator2 <- function(flcs1, catches, quant, year, unit, season, area, iter, value) {
    .Call('FLasher_test_FLCatches_assignment_operator2', PACKAGE = 'FLasher', flcs1, catches, quant, year, unit, season, area, iter, value)
}

test_FLCatches_function_operator <- function(flcs, flc) {
    .Call('FLasher_test_FLCatches_function_operator', PACKAGE = 'FLasher', flcs, flc)
}

test_FLCatches_get_ncatches <- function(flc_sexp1) {
    .Call('FLasher_test_FLCatches_get_ncatches', PACKAGE = 'FLasher', flc_sexp1)
}

test_FLCatches_const_get_single_index_accessor <- function(flcs, element) {
    .Call('FLasher_test_FLCatches_const_get_single_index_accessor', PACKAGE = 'FLasher', flcs, element)
}

test_FLCatches_get_single_index_accessor <- function(flcs, element) {
    .Call('FLasher_test_FLCatches_get_single_index_accessor', PACKAGE = 'FLasher', flcs, element)
}

test_FLCatches_const_get_value_accessor <- function(flcs, catches, quant, year, unit, season, area, iter) {
    .Call('FLasher_test_FLCatches_const_get_value_accessor', PACKAGE = 'FLasher', flcs, catches, quant, year, unit, season, area, iter)
}

test_FLCatches_get_value_accessor <- function(flcs, catches, quant, year, unit, season, area, iter) {
    .Call('FLasher_test_FLCatches_get_value_accessor', PACKAGE = 'FLasher', flcs, catches, quant, year, unit, season, area, iter)
}

test_FLCatches_set_single_index_accessor <- function(flcs, element, flc) {
    .Call('FLasher_test_FLCatches_set_single_index_accessor', PACKAGE = 'FLasher', flcs, element, flc)
}

test_FLCatches_set_value_accessor <- function(flcs, element, quant, year, unit, season, area, iter, value) {
    .Call('FLasher_test_FLCatches_set_value_accessor', PACKAGE = 'FLasher', flcs, element, quant, year, unit, season, area, iter, value)
}

test_FLCatches_const_get_single_index_default_accessor <- function(flcs) {
    .Call('FLasher_test_FLCatches_const_get_single_index_default_accessor', PACKAGE = 'FLasher', flcs)
}

test_FLCatches_get_single_index_default_accessor <- function(flcs) {
    .Call('FLasher_test_FLCatches_get_single_index_default_accessor', PACKAGE = 'FLasher', flcs)
}

test_FLCatches_set_single_index_default_accessor <- function(flcs, flc) {
    .Call('FLasher_test_FLCatches_set_single_index_default_accessor', PACKAGE = 'FLasher', flcs, flc)
}

test_FLCatchesAD_as_wrap <- function(flcs) {
    .Call('FLasher_test_FLCatchesAD_as_wrap', PACKAGE = 'FLasher', flcs)
}

test_FLCatchesAD_sexp_constructor <- function(flcs_sexp1) {
    .Call('FLasher_test_FLCatchesAD_sexp_constructor', PACKAGE = 'FLasher', flcs_sexp1)
}

test_FLCatchesAD_FLCatchAD_constructor <- function(flc) {
    .Call('FLasher_test_FLCatchesAD_FLCatchAD_constructor', PACKAGE = 'FLasher', flc)
}

test_FLCatchesAD_copy_constructor <- function(flcs) {
    .Call('FLasher_test_FLCatchesAD_copy_constructor', PACKAGE = 'FLasher', flcs)
}

test_FLCatchesAD_copy_constructor2 <- function(flcs1, catches, quant, year, unit, season, area, iter, value) {
    .Call('FLasher_test_FLCatchesAD_copy_constructor2', PACKAGE = 'FLasher', flcs1, catches, quant, year, unit, season, area, iter, value)
}

test_FLCatchesAD_assignment_operator <- function(flcs) {
    .Call('FLasher_test_FLCatchesAD_assignment_operator', PACKAGE = 'FLasher', flcs)
}

test_FLCatchesAD_assignment_operator2 <- function(flcs1, catches, quant, year, unit, season, area, iter, value) {
    .Call('FLasher_test_FLCatchesAD_assignment_operator2', PACKAGE = 'FLasher', flcs1, catches, quant, year, unit, season, area, iter, value)
}

test_FLCatchesAD_function_operator <- function(flcs, flc) {
    .Call('FLasher_test_FLCatchesAD_function_operator', PACKAGE = 'FLasher', flcs, flc)
}

test_FLCatchesAD_get_ncatches <- function(flc_sexp1) {
    .Call('FLasher_test_FLCatchesAD_get_ncatches', PACKAGE = 'FLasher', flc_sexp1)
}

test_FLCatchesAD_const_get_single_index_accessor <- function(flcs, element) {
    .Call('FLasher_test_FLCatchesAD_const_get_single_index_accessor', PACKAGE = 'FLasher', flcs, element)
}

test_FLCatchesAD_get_single_index_accessor <- function(flcs, element) {
    .Call('FLasher_test_FLCatchesAD_get_single_index_accessor', PACKAGE = 'FLasher', flcs, element)
}

test_FLCatchesAD_const_get_value_accessor <- function(flcs, catches, quant, year, unit, season, area, iter) {
    .Call('FLasher_test_FLCatchesAD_const_get_value_accessor', PACKAGE = 'FLasher', flcs, catches, quant, year, unit, season, area, iter)
}

test_FLCatchesAD_get_value_accessor <- function(flcs, catches, quant, year, unit, season, area, iter) {
    .Call('FLasher_test_FLCatchesAD_get_value_accessor', PACKAGE = 'FLasher', flcs, catches, quant, year, unit, season, area, iter)
}

test_FLCatchesAD_set_single_index_accessor <- function(flcs, element, flc) {
    .Call('FLasher_test_FLCatchesAD_set_single_index_accessor', PACKAGE = 'FLasher', flcs, element, flc)
}

test_FLCatchesAD_set_value_accessor <- function(flcs, element, quant, year, unit, season, area, iter, value) {
    .Call('FLasher_test_FLCatchesAD_set_value_accessor', PACKAGE = 'FLasher', flcs, element, quant, year, unit, season, area, iter, value)
}

test_FLCatchesAD_const_get_single_index_default_accessor <- function(flcs) {
    .Call('FLasher_test_FLCatchesAD_const_get_single_index_default_accessor', PACKAGE = 'FLasher', flcs)
}

test_FLCatchesAD_get_single_index_default_accessor <- function(flcs) {
    .Call('FLasher_test_FLCatchesAD_get_single_index_default_accessor', PACKAGE = 'FLasher', flcs)
}

test_FLCatchesAD_set_single_index_default_accessor <- function(flcs, flc) {
    .Call('FLasher_test_FLCatchesAD_set_single_index_default_accessor', PACKAGE = 'FLasher', flcs, flc)
}

test_FLFishery_empty_constructor <- function() {
    invisible(.Call('FLasher_test_FLFishery_empty_constructor', PACKAGE = 'FLasher'))
}

test_simple_FLFishery_sexp_constructor <- function(flf_sexp) {
    .Call('FLasher_test_simple_FLFishery_sexp_constructor', PACKAGE = 'FLasher', flf_sexp)
}

test_FLFishery_sexp_constructor <- function(flf_sexp) {
    .Call('FLasher_test_FLFishery_sexp_constructor', PACKAGE = 'FLasher', flf_sexp)
}

test_FLFishery_as_wrap <- function(flf) {
    .Call('FLasher_test_FLFishery_as_wrap', PACKAGE = 'FLasher', flf)
}

test_FLFishery_copy_constructor <- function(flf1) {
    .Call('FLasher_test_FLFishery_copy_constructor', PACKAGE = 'FLasher', flf1)
}

test_FLFishery_assignment_operator <- function(flf1) {
    .Call('FLasher_test_FLFishery_assignment_operator', PACKAGE = 'FLasher', flf1)
}

test_FLFishery_const_catches_get_accessors <- function(flf, catches, quant, year, unit, season, area, iter) {
    .Call('FLasher_test_FLFishery_const_catches_get_accessors', PACKAGE = 'FLasher', flf, catches, quant, year, unit, season, area, iter)
}

test_FLFishery_catches_get_accessors <- function(flf, catches, quant, year, unit, season, area, iter) {
    .Call('FLasher_test_FLFishery_catches_get_accessors', PACKAGE = 'FLasher', flf, catches, quant, year, unit, season, area, iter)
}

test_FLFishery_const_economics_get_accessors <- function(flf, quant, year, unit, season, area, iter) {
    .Call('FLasher_test_FLFishery_const_economics_get_accessors', PACKAGE = 'FLasher', flf, quant, year, unit, season, area, iter)
}

test_FLFishery_get_effort_subset <- function(flf, indices_min, indices_max) {
    .Call('FLasher_test_FLFishery_get_effort_subset', PACKAGE = 'FLasher', flf, indices_min, indices_max)
}

test_FLFishery_get_effort <- function(flf) {
    .Call('FLasher_test_FLFishery_get_effort', PACKAGE = 'FLasher', flf)
}

test_FLFishery_economics_get_accessors <- function(flf, quant, year, unit, season, area, iter) {
    .Call('FLasher_test_FLFishery_economics_get_accessors', PACKAGE = 'FLasher', flf, quant, year, unit, season, area, iter)
}

test_FLFishery_set_accessors <- function(flf, catches, quant, year, unit, season, area, iter, value) {
    .Call('FLasher_test_FLFishery_set_accessors', PACKAGE = 'FLasher', flf, catches, quant, year, unit, season, area, iter, value)
}

test_FLFishery_copy_constructor2 <- function(flf1, element, quant, year, unit, season, area, iter, value) {
    .Call('FLasher_test_FLFishery_copy_constructor2', PACKAGE = 'FLasher', flf1, element, quant, year, unit, season, area, iter, value)
}

test_FLFishery_assignment_operator2 <- function(flf1, element, quant, year, unit, season, area, iter, value) {
    .Call('FLasher_test_FLFishery_assignment_operator2', PACKAGE = 'FLasher', flf1, element, quant, year, unit, season, area, iter, value)
}

test_FLFisheryAD_empty_constructor <- function() {
    invisible(.Call('FLasher_test_FLFisheryAD_empty_constructor', PACKAGE = 'FLasher'))
}

test_simple_FLFisheryAD_sexp_constructor <- function(flf_sexp) {
    .Call('FLasher_test_simple_FLFisheryAD_sexp_constructor', PACKAGE = 'FLasher', flf_sexp)
}

test_FLFisheryAD_sexp_constructor <- function(flf_sexp) {
    .Call('FLasher_test_FLFisheryAD_sexp_constructor', PACKAGE = 'FLasher', flf_sexp)
}

test_FLFisheryAD_as_wrap <- function(flf) {
    .Call('FLasher_test_FLFisheryAD_as_wrap', PACKAGE = 'FLasher', flf)
}

test_FLFisheryAD_copy_constructor <- function(flf1) {
    .Call('FLasher_test_FLFisheryAD_copy_constructor', PACKAGE = 'FLasher', flf1)
}

test_FLFisheryAD_assignment_operator <- function(flf1) {
    .Call('FLasher_test_FLFisheryAD_assignment_operator', PACKAGE = 'FLasher', flf1)
}

test_FLFisheryAD_const_catches_get_accessors <- function(flf, catches, quant, year, unit, season, area, iter) {
    .Call('FLasher_test_FLFisheryAD_const_catches_get_accessors', PACKAGE = 'FLasher', flf, catches, quant, year, unit, season, area, iter)
}

test_FLFisheryAD_catches_get_accessors <- function(flf, catches, quant, year, unit, season, area, iter) {
    .Call('FLasher_test_FLFisheryAD_catches_get_accessors', PACKAGE = 'FLasher', flf, catches, quant, year, unit, season, area, iter)
}

test_FLFisheryAD_const_economics_get_accessors <- function(flf, quant, year, unit, season, area, iter) {
    .Call('FLasher_test_FLFisheryAD_const_economics_get_accessors', PACKAGE = 'FLasher', flf, quant, year, unit, season, area, iter)
}

test_FLFisheryAD_economics_get_accessors <- function(flf, quant, year, unit, season, area, iter) {
    .Call('FLasher_test_FLFisheryAD_economics_get_accessors', PACKAGE = 'FLasher', flf, quant, year, unit, season, area, iter)
}

test_FLFisheryAD_set_accessors <- function(flf, catches, quant, year, unit, season, area, iter, value) {
    .Call('FLasher_test_FLFisheryAD_set_accessors', PACKAGE = 'FLasher', flf, catches, quant, year, unit, season, area, iter, value)
}

test_FLFisheryAD_copy_constructor2 <- function(flf1, element, quant, year, unit, season, area, iter, value) {
    .Call('FLasher_test_FLFisheryAD_copy_constructor2', PACKAGE = 'FLasher', flf1, element, quant, year, unit, season, area, iter, value)
}

test_FLFisheryAD_assignment_operator2 <- function(flf1, element, quant, year, unit, season, area, iter, value) {
    .Call('FLasher_test_FLFisheryAD_assignment_operator2', PACKAGE = 'FLasher', flf1, element, quant, year, unit, season, area, iter, value)
}

test_FLFisheries_sexp_constructor <- function(flfs_sexp1) {
    .Call('FLasher_test_FLFisheries_sexp_constructor', PACKAGE = 'FLasher', flfs_sexp1)
}

test_FLFisheries_as_wrap <- function(flfs) {
    .Call('FLasher_test_FLFisheries_as_wrap', PACKAGE = 'FLasher', flfs)
}

test_FLFisheries_get_nfisheries <- function(flfs) {
    .Call('FLasher_test_FLFisheries_get_nfisheries', PACKAGE = 'FLasher', flfs)
}

test_FLFisheries_copy_constructor <- function(flfs) {
    .Call('FLasher_test_FLFisheries_copy_constructor', PACKAGE = 'FLasher', flfs)
}

test_FLFisheries_copy_constructor2 <- function(flfs1, fishery, catches, indices, value) {
    .Call('FLasher_test_FLFisheries_copy_constructor2', PACKAGE = 'FLasher', flfs1, fishery, catches, indices, value)
}

test_FLFisheries_assignment_operator <- function(flfs) {
    .Call('FLasher_test_FLFisheries_assignment_operator', PACKAGE = 'FLasher', flfs)
}

test_FLFisheries_assignment_operator2 <- function(flfs1, fishery, catches, indices, value) {
    .Call('FLasher_test_FLFisheries_assignment_operator2', PACKAGE = 'FLasher', flfs1, fishery, catches, indices, value)
}

test_FLFisheries_const_get_single <- function(flfs, fishery, catches, indices) {
    .Call('FLasher_test_FLFisheries_const_get_single', PACKAGE = 'FLasher', flfs, fishery, catches, indices)
}

test_FLFisheries_get_single <- function(flfs, fishery, catches, indices) {
    .Call('FLasher_test_FLFisheries_get_single', PACKAGE = 'FLasher', flfs, fishery, catches, indices)
}

test_FLFisheries_const_get_double <- function(flfs, fishery, catches, indices) {
    .Call('FLasher_test_FLFisheries_const_get_double', PACKAGE = 'FLasher', flfs, fishery, catches, indices)
}

test_FLFisheries_get_double <- function(flfs, fishery, catches, indices) {
    .Call('FLasher_test_FLFisheries_get_double', PACKAGE = 'FLasher', flfs, fishery, catches, indices)
}

test_FLFisheries_set_single <- function(flfs, fishery, catches, indices, value) {
    .Call('FLasher_test_FLFisheries_set_single', PACKAGE = 'FLasher', flfs, fishery, catches, indices, value)
}

test_FLFisheries_set_double <- function(flfs, fishery, catches, indices, value) {
    .Call('FLasher_test_FLFisheries_set_double', PACKAGE = 'FLasher', flfs, fishery, catches, indices, value)
}

test_FLFisheriesAD_sexp_constructor <- function(flfs_sexp1) {
    .Call('FLasher_test_FLFisheriesAD_sexp_constructor', PACKAGE = 'FLasher', flfs_sexp1)
}

test_FLFisheriesAD_as_wrap <- function(flfs) {
    .Call('FLasher_test_FLFisheriesAD_as_wrap', PACKAGE = 'FLasher', flfs)
}

test_FLFisheriesAD_get_nfisheries <- function(flfs) {
    .Call('FLasher_test_FLFisheriesAD_get_nfisheries', PACKAGE = 'FLasher', flfs)
}

test_FLFisheriesAD_copy_constructor <- function(flfs) {
    .Call('FLasher_test_FLFisheriesAD_copy_constructor', PACKAGE = 'FLasher', flfs)
}

test_FLFisheriesAD_copy_constructor2 <- function(flfs1, fishery, catches, indices, value) {
    .Call('FLasher_test_FLFisheriesAD_copy_constructor2', PACKAGE = 'FLasher', flfs1, fishery, catches, indices, value)
}

test_FLFisheriesAD_assignment_operator <- function(flfs) {
    .Call('FLasher_test_FLFisheriesAD_assignment_operator', PACKAGE = 'FLasher', flfs)
}

test_FLFisheriesAD_assignment_operator2 <- function(flfs1, fishery, catches, indices, value) {
    .Call('FLasher_test_FLFisheriesAD_assignment_operator2', PACKAGE = 'FLasher', flfs1, fishery, catches, indices, value)
}

test_FLFisheriesAD_const_get_single <- function(flfs, fishery, catches, indices) {
    .Call('FLasher_test_FLFisheriesAD_const_get_single', PACKAGE = 'FLasher', flfs, fishery, catches, indices)
}

test_FLFisheriesAD_get_single <- function(flfs, fishery, catches, indices) {
    .Call('FLasher_test_FLFisheriesAD_get_single', PACKAGE = 'FLasher', flfs, fishery, catches, indices)
}

test_FLFisheriesAD_const_get_double <- function(flfs, fishery, catches, indices) {
    .Call('FLasher_test_FLFisheriesAD_const_get_double', PACKAGE = 'FLasher', flfs, fishery, catches, indices)
}

test_FLFisheriesAD_get_double <- function(flfs, fishery, catches, indices) {
    .Call('FLasher_test_FLFisheriesAD_get_double', PACKAGE = 'FLasher', flfs, fishery, catches, indices)
}

test_FLFisheriesAD_set_single <- function(flfs, fishery, catches, indices, value) {
    .Call('FLasher_test_FLFisheriesAD_set_single', PACKAGE = 'FLasher', flfs, fishery, catches, indices, value)
}

test_FLFisheriesAD_set_double <- function(flfs, fishery, catches, indices, value) {
    .Call('FLasher_test_FLFisheriesAD_set_double', PACKAGE = 'FLasher', flfs, fishery, catches, indices, value)
}

test_FLQuantAD_as_wrap <- function(flq) {
    .Call('FLasher_test_FLQuantAD_as_wrap', PACKAGE = 'FLasher', flq)
}

test_FLQuantAD_basic_constructor <- function() {
    invisible(.Call('FLasher_test_FLQuantAD_basic_constructor', PACKAGE = 'FLasher'))
}

test_FLQuantAD_sexp_constructor <- function(flq_sexp) {
    .Call('FLasher_test_FLQuantAD_sexp_constructor', PACKAGE = 'FLasher', flq_sexp)
}

test_FLQuantAD_dim_constructor <- function(nquant, nyear, nunit, nseason, narea, niter) {
    .Call('FLasher_test_FLQuantAD_dim_constructor', PACKAGE = 'FLasher', nquant, nyear, nunit, nseason, narea, niter)
}

test_FLQuantAD_copy_constructor <- function(flq) {
    .Call('FLasher_test_FLQuantAD_copy_constructor', PACKAGE = 'FLasher', flq)
}

test_FLQuantAD_copy_constructor2 <- function(flq1, quant, year, unit, season, area, iter, value) {
    .Call('FLasher_test_FLQuantAD_copy_constructor2', PACKAGE = 'FLasher', flq1, quant, year, unit, season, area, iter, value)
}

test_FLQuantAD_assignment_operator <- function(flq) {
    .Call('FLasher_test_FLQuantAD_assignment_operator', PACKAGE = 'FLasher', flq)
}

test_FLQuantAD_assignment_operator2 <- function(flq1, quant, year, unit, season, area, iter, value) {
    .Call('FLasher_test_FLQuantAD_assignment_operator2', PACKAGE = 'FLasher', flq1, quant, year, unit, season, area, iter, value)
}

test_FLQuantAD_from_FLQuant_constructor <- function(flq) {
    .Call('FLasher_test_FLQuantAD_from_FLQuant_constructor', PACKAGE = 'FLasher', flq)
}

test_FLQuantAD_get_units <- function(flq) {
    .Call('FLasher_test_FLQuantAD_get_units', PACKAGE = 'FLasher', flq)
}

test_FLQuantAD_get_dim <- function(flq) {
    .Call('FLasher_test_FLQuantAD_get_dim', PACKAGE = 'FLasher', flq)
}

test_FLQuantAD_get_dimnames <- function(flq) {
    .Call('FLasher_test_FLQuantAD_get_dimnames', PACKAGE = 'FLasher', flq)
}

test_FLQuantAD_get_size <- function(flq) {
    .Call('FLasher_test_FLQuantAD_get_size', PACKAGE = 'FLasher', flq)
}

test_FLQuantAD_get_nquant <- function(flq) {
    .Call('FLasher_test_FLQuantAD_get_nquant', PACKAGE = 'FLasher', flq)
}

test_FLQuantAD_get_nyear <- function(flq) {
    .Call('FLasher_test_FLQuantAD_get_nyear', PACKAGE = 'FLasher', flq)
}

test_FLQuantAD_get_nunit <- function(flq) {
    .Call('FLasher_test_FLQuantAD_get_nunit', PACKAGE = 'FLasher', flq)
}

test_FLQuantAD_get_nseason <- function(flq) {
    .Call('FLasher_test_FLQuantAD_get_nseason', PACKAGE = 'FLasher', flq)
}

test_FLQuantAD_get_narea <- function(flq) {
    .Call('FLasher_test_FLQuantAD_get_narea', PACKAGE = 'FLasher', flq)
}

test_FLQuantAD_get_niter <- function(flq) {
    .Call('FLasher_test_FLQuantAD_get_niter', PACKAGE = 'FLasher', flq)
}

test_FLQuantAD_get_data_element <- function(flq, quant, year, unit, season, area, iter) {
    .Call('FLasher_test_FLQuantAD_get_data_element', PACKAGE = 'FLasher', flq, quant, year, unit, season, area, iter)
}

test_FLQuantAD_get_const_single_index_accessor <- function(flq, element) {
    .Call('FLasher_test_FLQuantAD_get_const_single_index_accessor', PACKAGE = 'FLasher', flq, element)
}

test_FLQuantAD_get_single_index_accessor <- function(flq, element) {
    .Call('FLasher_test_FLQuantAD_get_single_index_accessor', PACKAGE = 'FLasher', flq, element)
}

test_FLQuantAD_set_single_index_accessor <- function(flq, element, value) {
    .Call('FLasher_test_FLQuantAD_set_single_index_accessor', PACKAGE = 'FLasher', flq, element, value)
}

test_FLQuantAD_const_get_accessor <- function(flq, quant, year, unit, season, area, iter) {
    .Call('FLasher_test_FLQuantAD_const_get_accessor', PACKAGE = 'FLasher', flq, quant, year, unit, season, area, iter)
}

test_FLQuantAD_get_accessor <- function(flq, quant, year, unit, season, area, iter) {
    .Call('FLasher_test_FLQuantAD_get_accessor', PACKAGE = 'FLasher', flq, quant, year, unit, season, area, iter)
}

test_FLQuantAD_set_accessor <- function(flq, quant, year, unit, season, area, iter, value) {
    .Call('FLasher_test_FLQuantAD_set_accessor', PACKAGE = 'FLasher', flq, quant, year, unit, season, area, iter, value)
}

test_FLQuantAD_get_const_indices_accessor <- function(flq, indices) {
    .Call('FLasher_test_FLQuantAD_get_const_indices_accessor', PACKAGE = 'FLasher', flq, indices)
}

test_FLQuantAD_get_indices_accessor <- function(flq, indices) {
    .Call('FLasher_test_FLQuantAD_get_indices_accessor', PACKAGE = 'FLasher', flq, indices)
}

test_FLQuantAD_set_indices_accessor <- function(flq, indices, value) {
    .Call('FLasher_test_FLQuantAD_set_indices_accessor', PACKAGE = 'FLasher', flq, indices, value)
}

test_FLQuantAD_set_dimnames <- function(flq, new_dimnames) {
    .Call('FLasher_test_FLQuantAD_set_dimnames', PACKAGE = 'FLasher', flq, new_dimnames)
}

test_FLQuantAD_FLQuantAD_match_dims <- function(flq1, flq2) {
    .Call('FLasher_test_FLQuantAD_FLQuantAD_match_dims', PACKAGE = 'FLasher', flq1, flq2)
}

test_FLQuantAD_FLQuant_match_dims <- function(flq1, flq2) {
    .Call('FLasher_test_FLQuantAD_FLQuant_match_dims', PACKAGE = 'FLasher', flq1, flq2)
}

test_FLQuant_FLQuantAD_match_dims <- function(flq1, flq2) {
    .Call('FLasher_test_FLQuant_FLQuantAD_match_dims', PACKAGE = 'FLasher', flq1, flq2)
}

FLPar_units <- function(flp) {
    .Call('FLasher_FLPar_units', PACKAGE = 'FLasher', flp)
}

test_FLQuant_as_wrap <- function(flq) {
    .Call('FLasher_test_FLQuant_as_wrap', PACKAGE = 'FLasher', flq)
}

test_FLQuant_basic_constructor <- function() {
    invisible(.Call('FLasher_test_FLQuant_basic_constructor', PACKAGE = 'FLasher'))
}

test_FLQuant_sexp_constructor <- function(flq_sexp) {
    .Call('FLasher_test_FLQuant_sexp_constructor', PACKAGE = 'FLasher', flq_sexp)
}

test_FLQuant_dim_constructor <- function(nquant, nyear, nunit, nseason, narea, niter) {
    .Call('FLasher_test_FLQuant_dim_constructor', PACKAGE = 'FLasher', nquant, nyear, nunit, nseason, narea, niter)
}

test_FLQuant_copy_constructor <- function(flq) {
    .Call('FLasher_test_FLQuant_copy_constructor', PACKAGE = 'FLasher', flq)
}

test_FLQuant_copy_constructor2 <- function(flq1, quant, year, unit, season, area, iter, value) {
    .Call('FLasher_test_FLQuant_copy_constructor2', PACKAGE = 'FLasher', flq1, quant, year, unit, season, area, iter, value)
}

test_FLQuant_assignment_operator <- function(flq) {
    .Call('FLasher_test_FLQuant_assignment_operator', PACKAGE = 'FLasher', flq)
}

test_FLQuant_assignment_operator2 <- function(flq1, quant, year, unit, season, area, iter, value) {
    .Call('FLasher_test_FLQuant_assignment_operator2', PACKAGE = 'FLasher', flq1, quant, year, unit, season, area, iter, value)
}

test_FLQuant_get_data <- function(flq) {
    .Call('FLasher_test_FLQuant_get_data', PACKAGE = 'FLasher', flq)
}

test_FLQuant_get_units <- function(flq) {
    .Call('FLasher_test_FLQuant_get_units', PACKAGE = 'FLasher', flq)
}

test_FLQuant_get_dim <- function(flq) {
    .Call('FLasher_test_FLQuant_get_dim', PACKAGE = 'FLasher', flq)
}

test_FLQuant_get_dimnames <- function(flq) {
    .Call('FLasher_test_FLQuant_get_dimnames', PACKAGE = 'FLasher', flq)
}

test_FLQuant_get_dimnames2 <- function(flq) {
    .Call('FLasher_test_FLQuant_get_dimnames2', PACKAGE = 'FLasher', flq)
}

test_FLQuant_get_size <- function(flq) {
    .Call('FLasher_test_FLQuant_get_size', PACKAGE = 'FLasher', flq)
}

test_FLQuant_get_nquant <- function(flq) {
    .Call('FLasher_test_FLQuant_get_nquant', PACKAGE = 'FLasher', flq)
}

test_FLQuant_get_nyear <- function(flq) {
    .Call('FLasher_test_FLQuant_get_nyear', PACKAGE = 'FLasher', flq)
}

test_FLQuant_get_nunit <- function(flq) {
    .Call('FLasher_test_FLQuant_get_nunit', PACKAGE = 'FLasher', flq)
}

test_FLQuant_get_nseason <- function(flq) {
    .Call('FLasher_test_FLQuant_get_nseason', PACKAGE = 'FLasher', flq)
}

test_FLQuant_get_narea <- function(flq) {
    .Call('FLasher_test_FLQuant_get_narea', PACKAGE = 'FLasher', flq)
}

test_FLQuant_get_niter <- function(flq) {
    .Call('FLasher_test_FLQuant_get_niter', PACKAGE = 'FLasher', flq)
}

test_FLQuant_get_data_element <- function(flq, quant, year, unit, season, area, iter) {
    .Call('FLasher_test_FLQuant_get_data_element', PACKAGE = 'FLasher', flq, quant, year, unit, season, area, iter)
}

test_FLQuant_get_const_single_index_accessor <- function(flq, element) {
    .Call('FLasher_test_FLQuant_get_const_single_index_accessor', PACKAGE = 'FLasher', flq, element)
}

test_FLQuant_get_single_index_accessor <- function(flq, element) {
    .Call('FLasher_test_FLQuant_get_single_index_accessor', PACKAGE = 'FLasher', flq, element)
}

test_FLQuant_set_single_index_accessor <- function(flq, element, value) {
    .Call('FLasher_test_FLQuant_set_single_index_accessor', PACKAGE = 'FLasher', flq, element, value)
}

test_FLQuant_const_get_accessor <- function(flq, quant, year, unit, season, area, iter) {
    .Call('FLasher_test_FLQuant_const_get_accessor', PACKAGE = 'FLasher', flq, quant, year, unit, season, area, iter)
}

test_FLQuant_get_accessor <- function(flq, quant, year, unit, season, area, iter) {
    .Call('FLasher_test_FLQuant_get_accessor', PACKAGE = 'FLasher', flq, quant, year, unit, season, area, iter)
}

test_FLQuant_set_accessor <- function(flq, quant, year, unit, season, area, iter, value) {
    .Call('FLasher_test_FLQuant_set_accessor', PACKAGE = 'FLasher', flq, quant, year, unit, season, area, iter, value)
}

test_FLQuant_get_const_indices_accessor <- function(flq, indices) {
    .Call('FLasher_test_FLQuant_get_const_indices_accessor', PACKAGE = 'FLasher', flq, indices)
}

test_FLQuant_get_indices_accessor <- function(flq, indices) {
    .Call('FLasher_test_FLQuant_get_indices_accessor', PACKAGE = 'FLasher', flq, indices)
}

test_FLQuant_set_indices_accessor <- function(flq, indices, value) {
    .Call('FLasher_test_FLQuant_set_indices_accessor', PACKAGE = 'FLasher', flq, indices, value)
}

test_FLQuant_get_all_iters <- function(flq, quant, year, unit, season, area) {
    .Call('FLasher_test_FLQuant_get_all_iters', PACKAGE = 'FLasher', flq, quant, year, unit, season, area)
}

test_FLQuant_set_data <- function(flq, data_in) {
    .Call('FLasher_test_FLQuant_set_data', PACKAGE = 'FLasher', flq, data_in)
}

test_FLQuant_set_dimnames <- function(flq, new_dimnames) {
    .Call('FLasher_test_FLQuant_set_dimnames', PACKAGE = 'FLasher', flq, new_dimnames)
}

test_FLQuant_set_units <- function(flq, new_units) {
    .Call('FLasher_test_FLQuant_set_units', PACKAGE = 'FLasher', flq, new_units)
}

test_FLQuant_subset <- function(flq, quant_min, quant_max, year_min, year_max, unit_min, unit_max, season_min, season_max, area_min, area_max, iter_min, iter_max) {
    .Call('FLasher_test_FLQuant_subset', PACKAGE = 'FLasher', flq, quant_min, quant_max, year_min, year_max, unit_min, unit_max, season_min, season_max, area_min, area_max, iter_min, iter_max)
}

test_FLQuant_neat_subset <- function(flq, indices_min, indices_max) {
    .Call('FLasher_test_FLQuant_neat_subset', PACKAGE = 'FLasher', flq, indices_min, indices_max)
}

test_FLQuant_propagate_iters <- function(flq, iters) {
    .Call('FLasher_test_FLQuant_propagate_iters', PACKAGE = 'FLasher', flq, iters)
}

test_FLQuant_fill <- function(flq, value) {
    .Call('FLasher_test_FLQuant_fill', PACKAGE = 'FLasher', flq, value)
}

test_FLQuantAD_fill <- function(flq, value) {
    .Call('FLasher_test_FLQuantAD_fill', PACKAGE = 'FLasher', flq, value)
}

test_FLQuantAD_fill_double <- function(flq, value) {
    .Call('FLasher_test_FLQuantAD_fill_double', PACKAGE = 'FLasher', flq, value)
}

test_FLQuant_FLQuant_match_dims <- function(flq1, flq2) {
    .Call('FLasher_test_FLQuant_FLQuant_match_dims', PACKAGE = 'FLasher', flq1, flq2)
}

test_FLPar_to_FLQuant <- function(flp) {
    .Call('FLasher_test_FLPar_to_FLQuant', PACKAGE = 'FLasher', flp)
}

test_for_range <- function(flq, rn) {
    .Call('FLasher_test_for_range', PACKAGE = 'FLasher', flq, rn)
}

test_for_range_const <- function(flq, rn) {
    .Call('FLasher_test_for_range_const', PACKAGE = 'FLasher', flq, rn)
}

test_FLQuant_for_iterator <- function(flq, rn) {
    .Call('FLasher_test_FLQuant_for_iterator', PACKAGE = 'FLasher', flq, rn)
}

test_FLQuant_for_iterator_const <- function(flq, rn) {
    .Call('FLasher_test_FLQuant_for_iterator_const', PACKAGE = 'FLasher', flq, rn)
}

test_FLQuant_lambda <- function(flq1, flq2) {
    .Call('FLasher_test_FLQuant_lambda', PACKAGE = 'FLasher', flq1, flq2)
}

test_FLQuant7_as_wrap <- function(flq7) {
    .Call('FLasher_test_FLQuant7_as_wrap', PACKAGE = 'FLasher', flq7)
}

test_FLQuant7_empty_wrap <- function() {
    .Call('FLasher_test_FLQuant7_empty_wrap', PACKAGE = 'FLasher')
}

test_FLQuant7_basic_constructor <- function() {
    invisible(.Call('FLasher_test_FLQuant7_basic_constructor', PACKAGE = 'FLasher'))
}

test_FLQuant7_sexp_constructor <- function(flq_sexp1) {
    .Call('FLasher_test_FLQuant7_sexp_constructor', PACKAGE = 'FLasher', flq_sexp1)
}

test_FLQuant7_FLQuant_constructor <- function(flq) {
    .Call('FLasher_test_FLQuant7_FLQuant_constructor', PACKAGE = 'FLasher', flq)
}

test_FLQuant7_copy_constructor <- function(flq7) {
    .Call('FLasher_test_FLQuant7_copy_constructor', PACKAGE = 'FLasher', flq7)
}

test_FLQuant7_copy_constructor2 <- function(flq71, dim7, quant, year, unit, season, area, iter, value) {
    .Call('FLasher_test_FLQuant7_copy_constructor2', PACKAGE = 'FLasher', flq71, dim7, quant, year, unit, season, area, iter, value)
}

test_FLQuant7_assignment_operator <- function(flq7) {
    .Call('FLasher_test_FLQuant7_assignment_operator', PACKAGE = 'FLasher', flq7)
}

test_FLQuant7_assignment_operator2 <- function(flq71, dim7, quant, year, unit, season, area, iter, value) {
    .Call('FLasher_test_FLQuant7_assignment_operator2', PACKAGE = 'FLasher', flq71, dim7, quant, year, unit, season, area, iter, value)
}

test_FLQuant7_function_operator <- function(flq7, flq) {
    .Call('FLasher_test_FLQuant7_function_operator', PACKAGE = 'FLasher', flq7, flq)
}

test_FLQuant7_get_ndim7 <- function(flq_sexp1) {
    .Call('FLasher_test_FLQuant7_get_ndim7', PACKAGE = 'FLasher', flq_sexp1)
}

test_FLQuant7_const_get_single_index_accessor <- function(flq7, element) {
    .Call('FLasher_test_FLQuant7_const_get_single_index_accessor', PACKAGE = 'FLasher', flq7, element)
}

test_FLQuant7_get_single_index_accessor <- function(flq7, element) {
    .Call('FLasher_test_FLQuant7_get_single_index_accessor', PACKAGE = 'FLasher', flq7, element)
}

test_FLQuant7_set_single_index_accessor <- function(flq7, element, flq) {
    .Call('FLasher_test_FLQuant7_set_single_index_accessor', PACKAGE = 'FLasher', flq7, element, flq)
}

test_FLQuant7_const_get_accessor <- function(flq7, dim7, quant, year, unit, season, area, iter) {
    .Call('FLasher_test_FLQuant7_const_get_accessor', PACKAGE = 'FLasher', flq7, dim7, quant, year, unit, season, area, iter)
}

test_FLQuant7_get_accessor <- function(flq7, dim7, quant, year, unit, season, area, iter) {
    .Call('FLasher_test_FLQuant7_get_accessor', PACKAGE = 'FLasher', flq7, dim7, quant, year, unit, season, area, iter)
}

test_FLQuant7_set_accessor <- function(flq7, dim7, quant, year, unit, season, area, iter, value) {
    .Call('FLasher_test_FLQuant7_set_accessor', PACKAGE = 'FLasher', flq7, dim7, quant, year, unit, season, area, iter, value)
}

test_FLQuant7_const_default_dim7_get_accessor <- function(flq7) {
    .Call('FLasher_test_FLQuant7_const_default_dim7_get_accessor', PACKAGE = 'FLasher', flq7)
}

test_FLQuant7_default_dim7_get_accessor <- function(flq7) {
    .Call('FLasher_test_FLQuant7_default_dim7_get_accessor', PACKAGE = 'FLasher', flq7)
}

test_FLQuant7_default_dim7_set_accessor <- function(flq7, flq) {
    .Call('FLasher_test_FLQuant7_default_dim7_set_accessor', PACKAGE = 'FLasher', flq7, flq)
}

test_FLQuant7_const_default_dim7_get_accessor_multi <- function(flq7, quant, year, unit, season, area, iter) {
    .Call('FLasher_test_FLQuant7_const_default_dim7_get_accessor_multi', PACKAGE = 'FLasher', flq7, quant, year, unit, season, area, iter)
}

test_FLQuant7_default_dim7_get_accessor_multi <- function(flq7, quant, year, unit, season, area, iter) {
    .Call('FLasher_test_FLQuant7_default_dim7_get_accessor_multi', PACKAGE = 'FLasher', flq7, quant, year, unit, season, area, iter)
}

test_FLQuant7_default_dim7_set_accessor_multi <- function(flq7, quant, year, unit, season, area, iter, value) {
    .Call('FLasher_test_FLQuant7_default_dim7_set_accessor_multi', PACKAGE = 'FLasher', flq7, quant, year, unit, season, area, iter, value)
}

test_FLQuant7AD_as_wrap <- function(flq7) {
    .Call('FLasher_test_FLQuant7AD_as_wrap', PACKAGE = 'FLasher', flq7)
}

test_FLQuant7AD_empty_wrap <- function() {
    .Call('FLasher_test_FLQuant7AD_empty_wrap', PACKAGE = 'FLasher')
}

test_FLQuant7AD_basic_constructor <- function() {
    invisible(.Call('FLasher_test_FLQuant7AD_basic_constructor', PACKAGE = 'FLasher'))
}

test_FLQuant7AD_sexp_constructor <- function(flq_sexp1) {
    .Call('FLasher_test_FLQuant7AD_sexp_constructor', PACKAGE = 'FLasher', flq_sexp1)
}

test_FLQuant7AD_FLQuant_constructor <- function(flq) {
    .Call('FLasher_test_FLQuant7AD_FLQuant_constructor', PACKAGE = 'FLasher', flq)
}

test_FLQuant7AD_copy_constructor <- function(flq7) {
    .Call('FLasher_test_FLQuant7AD_copy_constructor', PACKAGE = 'FLasher', flq7)
}

test_FLQuant7AD_copy_constructor2 <- function(flq71, dim7, quant, year, unit, season, area, iter, value) {
    .Call('FLasher_test_FLQuant7AD_copy_constructor2', PACKAGE = 'FLasher', flq71, dim7, quant, year, unit, season, area, iter, value)
}

test_FLQuant7AD_assignment_operator <- function(flq7) {
    .Call('FLasher_test_FLQuant7AD_assignment_operator', PACKAGE = 'FLasher', flq7)
}

test_FLQuant7AD_assignment_operator2 <- function(flq71, dim7, quant, year, unit, season, area, iter, value) {
    .Call('FLasher_test_FLQuant7AD_assignment_operator2', PACKAGE = 'FLasher', flq71, dim7, quant, year, unit, season, area, iter, value)
}

test_FLQuant7AD_function_operator <- function(flq7, flq) {
    .Call('FLasher_test_FLQuant7AD_function_operator', PACKAGE = 'FLasher', flq7, flq)
}

test_FLQuant7AD_get_ndim7 <- function(flq_sexp1) {
    .Call('FLasher_test_FLQuant7AD_get_ndim7', PACKAGE = 'FLasher', flq_sexp1)
}

test_FLQuant7AD_const_get_single_index_accessor <- function(flq7, element) {
    .Call('FLasher_test_FLQuant7AD_const_get_single_index_accessor', PACKAGE = 'FLasher', flq7, element)
}

test_FLQuant7AD_get_single_index_accessor <- function(flq7, element) {
    .Call('FLasher_test_FLQuant7AD_get_single_index_accessor', PACKAGE = 'FLasher', flq7, element)
}

test_FLQuant7AD_set_single_index_accessor <- function(flq7, element, flq) {
    .Call('FLasher_test_FLQuant7AD_set_single_index_accessor', PACKAGE = 'FLasher', flq7, element, flq)
}

test_FLQuant7AD_const_get_accessor <- function(flq7, dim7, quant, year, unit, season, area, iter) {
    .Call('FLasher_test_FLQuant7AD_const_get_accessor', PACKAGE = 'FLasher', flq7, dim7, quant, year, unit, season, area, iter)
}

test_FLQuant7AD_get_accessor <- function(flq7, dim7, quant, year, unit, season, area, iter) {
    .Call('FLasher_test_FLQuant7AD_get_accessor', PACKAGE = 'FLasher', flq7, dim7, quant, year, unit, season, area, iter)
}

test_FLQuant7AD_set_accessor <- function(flq7, dim7, quant, year, unit, season, area, iter, value) {
    .Call('FLasher_test_FLQuant7AD_set_accessor', PACKAGE = 'FLasher', flq7, dim7, quant, year, unit, season, area, iter, value)
}

test_FLQuant7AD_const_default_dim7_get_accessor <- function(flq7) {
    .Call('FLasher_test_FLQuant7AD_const_default_dim7_get_accessor', PACKAGE = 'FLasher', flq7)
}

test_FLQuant7AD_default_dim7_get_accessor <- function(flq7) {
    .Call('FLasher_test_FLQuant7AD_default_dim7_get_accessor', PACKAGE = 'FLasher', flq7)
}

test_FLQuant7AD_default_dim7_set_accessor <- function(flq7, flq) {
    .Call('FLasher_test_FLQuant7AD_default_dim7_set_accessor', PACKAGE = 'FLasher', flq7, flq)
}

test_FLQuant7AD_const_default_dim7_get_accessor_multi <- function(flq7, quant, year, unit, season, area, iter) {
    .Call('FLasher_test_FLQuant7AD_const_default_dim7_get_accessor_multi', PACKAGE = 'FLasher', flq7, quant, year, unit, season, area, iter)
}

test_FLQuant7AD_default_dim7_get_accessor_multi <- function(flq7, quant, year, unit, season, area, iter) {
    .Call('FLasher_test_FLQuant7AD_default_dim7_get_accessor_multi', PACKAGE = 'FLasher', flq7, quant, year, unit, season, area, iter)
}

test_FLQuant7AD_default_dim7_set_accessor_multi <- function(flq7, quant, year, unit, season, area, iter, value) {
    .Call('FLasher_test_FLQuant7AD_default_dim7_set_accessor_multi', PACKAGE = 'FLasher', flq7, quant, year, unit, season, area, iter, value)
}

test_FLQ_in_FLS <- function(flq) {
    .Call('FLasher_test_FLQ_in_FLS', PACKAGE = 'FLasher', flq)
}

test_FLStock_sexp_constructor <- function(fls_sexp) {
    .Call('FLasher_test_FLStock_sexp_constructor', PACKAGE = 'FLasher', fls_sexp)
}

test_FLStock_wrap <- function(fls_sexp) {
    .Call('FLasher_test_FLStock_wrap', PACKAGE = 'FLasher', fls_sexp)
}

test_FLStock_as <- function(fls) {
    .Call('FLasher_test_FLStock_as', PACKAGE = 'FLasher', fls)
}

test_FLStock_as_wrap <- function(fls) {
    .Call('FLasher_test_FLStock_as_wrap', PACKAGE = 'FLasher', fls)
}

test_FLStock_copy_constructor <- function(fls1, quant, year, unit, season, area, iter, value) {
    .Call('FLasher_test_FLStock_copy_constructor', PACKAGE = 'FLasher', fls1, quant, year, unit, season, area, iter, value)
}

test_FLStock_assignment_operator <- function(fls1, quant, year, unit, season, area, iter, value) {
    .Call('FLasher_test_FLStock_assignment_operator', PACKAGE = 'FLasher', fls1, quant, year, unit, season, area, iter, value)
}

test_fwdBiol_sexp_constructor <- function(flb_sexp) {
    .Call('FLasher_test_fwdBiol_sexp_constructor', PACKAGE = 'FLasher', flb_sexp)
}

test_fwdBiolAD_sexp_constructor <- function(flb_sexp) {
    .Call('FLasher_test_fwdBiolAD_sexp_constructor', PACKAGE = 'FLasher', flb_sexp)
}

test_fwdBiol_as_wrap <- function(fwdb) {
    .Call('FLasher_test_fwdBiol_as_wrap', PACKAGE = 'FLasher', fwdb)
}

test_fwdBiolAD_as_wrap <- function(fwdb) {
    .Call('FLasher_test_fwdBiolAD_as_wrap', PACKAGE = 'FLasher', fwdb)
}

test_fwdBiol_fwdSR_constructor <- function(flb_sexp, model_name, params, timelag, residuals, residuals_mult) {
    .Call('FLasher_test_fwdBiol_fwdSR_constructor', PACKAGE = 'FLasher', flb_sexp, model_name, params, timelag, residuals, residuals_mult)
}

test_fwdBiol_FLSR_bits_constructor <- function(flb_sexp, model_name, params, timelag, residuals, residuals_mult) {
    .Call('FLasher_test_fwdBiol_FLSR_bits_constructor', PACKAGE = 'FLasher', flb_sexp, model_name, params, timelag, residuals, residuals_mult)
}

test_fwdBiolAD_fwdSRAD_constructor <- function(flb_sexp, model_name, params, timelag, residuals, residuals_mult) {
    .Call('FLasher_test_fwdBiolAD_fwdSRAD_constructor', PACKAGE = 'FLasher', flb_sexp, model_name, params, timelag, residuals, residuals_mult)
}

test_fwdBiolAD_FLSR_bits_constructor <- function(flb_sexp, model_name, params, timelag, residuals, residuals_mult) {
    .Call('FLasher_test_fwdBiolAD_FLSR_bits_constructor', PACKAGE = 'FLasher', flb_sexp, model_name, params, timelag, residuals, residuals_mult)
}

test_fwdBiol_copy_constructor <- function(fwdb1) {
    .Call('FLasher_test_fwdBiol_copy_constructor', PACKAGE = 'FLasher', fwdb1)
}

test_fwdBiolAD_copy_constructor <- function(fwdb1) {
    .Call('FLasher_test_fwdBiolAD_copy_constructor', PACKAGE = 'FLasher', fwdb1)
}

test_fwdBiol_copy_constructor2 <- function(fwdb1, quant, year, unit, season, area, iter, value) {
    .Call('FLasher_test_fwdBiol_copy_constructor2', PACKAGE = 'FLasher', fwdb1, quant, year, unit, season, area, iter, value)
}

test_fwdBiolAD_copy_constructor2 <- function(fwdb1, quant, year, unit, season, area, iter, value) {
    .Call('FLasher_test_fwdBiolAD_copy_constructor2', PACKAGE = 'FLasher', fwdb1, quant, year, unit, season, area, iter, value)
}

test_fwdBiol_assignment_operator <- function(fwdb1) {
    .Call('FLasher_test_fwdBiol_assignment_operator', PACKAGE = 'FLasher', fwdb1)
}

test_fwdBiolAD_assignment_operator <- function(fwdb1) {
    .Call('FLasher_test_fwdBiolAD_assignment_operator', PACKAGE = 'FLasher', fwdb1)
}

test_fwdBiol_assignment_operator2 <- function(fwdb1, quant, year, unit, season, area, iter, value) {
    .Call('FLasher_test_fwdBiol_assignment_operator2', PACKAGE = 'FLasher', fwdb1, quant, year, unit, season, area, iter, value)
}

test_fwdBiolAD_assignment_operator2 <- function(fwdb1, quant, year, unit, season, area, iter, value) {
    .Call('FLasher_test_fwdBiolAD_assignment_operator2', PACKAGE = 'FLasher', fwdb1, quant, year, unit, season, area, iter, value)
}

test_fwdBiol_const_get_accessors <- function(fwdb, quant, year, unit, season, area, iter) {
    .Call('FLasher_test_fwdBiol_const_get_accessors', PACKAGE = 'FLasher', fwdb, quant, year, unit, season, area, iter)
}

test_fwdBiol_get_accessors <- function(fwdb, quant, year, unit, season, area, iter) {
    .Call('FLasher_test_fwdBiol_get_accessors', PACKAGE = 'FLasher', fwdb, quant, year, unit, season, area, iter)
}

test_fwdBiolAD_const_get_accessors <- function(fwdb, quant, year, unit, season, area, iter) {
    .Call('FLasher_test_fwdBiolAD_const_get_accessors', PACKAGE = 'FLasher', fwdb, quant, year, unit, season, area, iter)
}

test_fwdBiolAD_get_accessors <- function(fwdb, quant, year, unit, season, area, iter) {
    .Call('FLasher_test_fwdBiolAD_get_accessors', PACKAGE = 'FLasher', fwdb, quant, year, unit, season, area, iter)
}

test_fwdBiol_set_accessors <- function(fwdb, quant, year, unit, season, area, iter, values) {
    .Call('FLasher_test_fwdBiol_set_accessors', PACKAGE = 'FLasher', fwdb, quant, year, unit, season, area, iter, values)
}

test_fwdBiolAD_set_accessors <- function(fwdb, quant, year, unit, season, area, iter, values) {
    .Call('FLasher_test_fwdBiolAD_set_accessors', PACKAGE = 'FLasher', fwdb, quant, year, unit, season, area, iter, values)
}

fwdBiolAD_biomass_FLQ <- function(fwdb) {
    .Call('FLasher_fwdBiolAD_biomass_FLQ', PACKAGE = 'FLasher', fwdb)
}

fwdBiolAD_biomass_subset <- function(fwdb, indices_min, indices_max) {
    .Call('FLasher_fwdBiolAD_biomass_subset', PACKAGE = 'FLasher', fwdb, indices_min, indices_max)
}

test_fwdBiols_list_constructor <- function(flbs_list_sexp) {
    .Call('FLasher_test_fwdBiols_list_constructor', PACKAGE = 'FLasher', flbs_list_sexp)
}

test_fwdBiolsAD_list_constructor <- function(flbs_list_sexp) {
    .Call('FLasher_test_fwdBiolsAD_list_constructor', PACKAGE = 'FLasher', flbs_list_sexp)
}

test_fwdBiols_fwdBiol_constructor <- function(flb_sexp, model_name, params, timelag, residuals, residuals_mult) {
    .Call('FLasher_test_fwdBiols_fwdBiol_constructor', PACKAGE = 'FLasher', flb_sexp, model_name, params, timelag, residuals, residuals_mult)
}

test_fwdBiolsAD_const_get_single_index_accessor <- function(fwbs_list_sexp, element) {
    .Call('FLasher_test_fwdBiolsAD_const_get_single_index_accessor', PACKAGE = 'FLasher', fwbs_list_sexp, element)
}

test_fwdBiolsAD_get_single_index_accessor <- function(fwbs_list_sexp, element) {
    .Call('FLasher_test_fwdBiolsAD_get_single_index_accessor', PACKAGE = 'FLasher', fwbs_list_sexp, element)
}

test_fwdBiolsAD_const_get_value_accessor <- function(fwbs_list_sexp, biol_no, quant, year, unit, season, area, iter) {
    .Call('FLasher_test_fwdBiolsAD_const_get_value_accessor', PACKAGE = 'FLasher', fwbs_list_sexp, biol_no, quant, year, unit, season, area, iter)
}

test_fwdBiolsAD_get_value_accessor <- function(fwbs_list_sexp, biol_no, quant, year, unit, season, area, iter) {
    .Call('FLasher_test_fwdBiolsAD_get_value_accessor', PACKAGE = 'FLasher', fwbs_list_sexp, biol_no, quant, year, unit, season, area, iter)
}

test_fwdBiolsAD_set_single_index_accessor <- function(fwbs_list_sexp, element, flb_sexp, model_name, params, timelag, residuals, residuals_mult) {
    .Call('FLasher_test_fwdBiolsAD_set_single_index_accessor', PACKAGE = 'FLasher', fwbs_list_sexp, element, flb_sexp, model_name, params, timelag, residuals, residuals_mult)
}

test_fwdBiolsAD_set_value_accessor <- function(fwbs_list_sexp, biol_no, quant, year, unit, season, area, iter, value) {
    .Call('FLasher_test_fwdBiolsAD_set_value_accessor', PACKAGE = 'FLasher', fwbs_list_sexp, biol_no, quant, year, unit, season, area, iter, value)
}

test_fwdBiolsAD_copy_constructor <- function(fwbs_list_sexp, biol_no, dims, value) {
    .Call('FLasher_test_fwdBiolsAD_copy_constructor', PACKAGE = 'FLasher', fwbs_list_sexp, biol_no, dims, value)
}

test_fwdBiolsAD_assignment_operator <- function(fwbs_list_sexp, biol_no, dims, value) {
    .Call('FLasher_test_fwdBiolsAD_assignment_operator', PACKAGE = 'FLasher', fwbs_list_sexp, biol_no, dims, value)
}

test_as_wrap_fwdControl <- function(control) {
    .Call('FLasher_test_as_wrap_fwdControl', PACKAGE = 'FLasher', control)
}

test_fwdControl_copy_constructor <- function(fc1) {
    .Call('FLasher_test_fwdControl_copy_constructor', PACKAGE = 'FLasher', fc1)
}

test_fwdControl_assignment_operator <- function(fc) {
    .Call('FLasher_test_fwdControl_assignment_operator', PACKAGE = 'FLasher', fc)
}

test_fwdControl_get_target <- function(control) {
    .Call('FLasher_test_fwdControl_get_target', PACKAGE = 'FLasher', control)
}

test_fwdControl_get_ntarget <- function(control) {
    .Call('FLasher_test_fwdControl_get_ntarget', PACKAGE = 'FLasher', control)
}

test_fwdControl_get_niter <- function(control) {
    .Call('FLasher_test_fwdControl_get_niter', PACKAGE = 'FLasher', control)
}

test_fwdControl_get_target_fishery <- function(control, target_no) {
    .Call('FLasher_test_fwdControl_get_target_fishery', PACKAGE = 'FLasher', control, target_no)
}

test_fwdControl_get_target_year <- function(control, target_no) {
    .Call('FLasher_test_fwdControl_get_target_year', PACKAGE = 'FLasher', control, target_no)
}

test_fwdControl_get_target_season <- function(control, target_no) {
    .Call('FLasher_test_fwdControl_get_target_season', PACKAGE = 'FLasher', control, target_no)
}

test_fwdControl_get_target_rel_year <- function(control, target_no) {
    .Call('FLasher_test_fwdControl_get_target_rel_year', PACKAGE = 'FLasher', control, target_no)
}

test_fwdControl_get_target_rel_season <- function(control, target_no) {
    .Call('FLasher_test_fwdControl_get_target_rel_season', PACKAGE = 'FLasher', control, target_no)
}

test_fwdControl_get_target_value <- function(control, target_no, col, iter) {
    .Call('FLasher_test_fwdControl_get_target_value', PACKAGE = 'FLasher', control, target_no, col, iter)
}

test_fwdControl_get_target_quantity <- function(control, target_no) {
    .Call('FLasher_test_fwdControl_get_target_quantity', PACKAGE = 'FLasher', control, target_no)
}

test_fwdControl_get_age_range <- function(control, target_no) {
    .Call('FLasher_test_fwdControl_get_age_range', PACKAGE = 'FLasher', control, target_no)
}

test_fwdControl_get_FC <- function(control, biol_no) {
    .Call('FLasher_test_fwdControl_get_FC', PACKAGE = 'FLasher', control, biol_no)
}

test_fwdControl_get_B <- function(control, fishery_no, catch_no) {
    .Call('FLasher_test_fwdControl_get_B', PACKAGE = 'FLasher', control, fishery_no, catch_no)
}

test_fwdSR_empty_constructor <- function() {
    invisible(.Call('FLasher_test_fwdSR_empty_constructor', PACKAGE = 'FLasher'))
}

test_fwdSR_constructor_wrap <- function(model_name, params, timelag, residuals, residuals_mult) {
    .Call('FLasher_test_fwdSR_constructor_wrap', PACKAGE = 'FLasher', model_name, params, timelag, residuals, residuals_mult)
}

test_fwdSR_constructor_value <- function(model_name, params, timelag, residuals, residuals_mult, ssb) {
    .Call('FLasher_test_fwdSR_constructor_value', PACKAGE = 'FLasher', model_name, params, timelag, residuals, residuals_mult, ssb)
}

test_fwdSR_get_nparams <- function(model_name, params, timelag, residuals, residuals_mult) {
    .Call('FLasher_test_fwdSR_get_nparams', PACKAGE = 'FLasher', model_name, params, timelag, residuals, residuals_mult)
}

test_fwdSR_eval_simple <- function(model_name, params, timelag, residuals, residuals_mult, ssb) {
    .Call('FLasher_test_fwdSR_eval_simple', PACKAGE = 'FLasher', model_name, params, timelag, residuals, residuals_mult, ssb)
}

test_fwdSR_eval_full <- function(model_name, params, timelag, residuals, residuals_mult, ssb, year, unit, season, area, iter) {
    .Call('FLasher_test_fwdSR_eval_full', PACKAGE = 'FLasher', model_name, params, timelag, residuals, residuals_mult, ssb, year, unit, season, area, iter)
}

test_fwdSR_copy_constructor <- function(model_name, params, timelag, residuals, residuals_mult, ssb) {
    .Call('FLasher_test_fwdSR_copy_constructor', PACKAGE = 'FLasher', model_name, params, timelag, residuals, residuals_mult, ssb)
}

test_fwdSR_assignment_operator <- function(model_name, params, timelag, residuals, residuals_mult, ssb) {
    .Call('FLasher_test_fwdSR_assignment_operator', PACKAGE = 'FLasher', model_name, params, timelag, residuals, residuals_mult, ssb)
}

test_fwdSR_get_timelag <- function(model_name, params, timelag, residuals, residuals_mult) {
    .Call('FLasher_test_fwdSR_get_timelag', PACKAGE = 'FLasher', model_name, params, timelag, residuals, residuals_mult)
}

test_euclid_norm <- function(xvec) {
    .Call('FLasher_test_euclid_norm', PACKAGE = 'FLasher', xvec)
}

test_NR1 <- function(initial_value, max_iters, max_limit, tolerance) {
    .Call('FLasher_test_NR1', PACKAGE = 'FLasher', initial_value, max_iters, max_limit, tolerance)
}

test_NR2 <- function(initial_value, max_iters, max_limit, tolerance) {
    .Call('FLasher_test_NR2', PACKAGE = 'FLasher', initial_value, max_iters, max_limit, tolerance)
}

test_year_season_to_timestep_FLQuant_double <- function(flq, year, season) {
    .Call('FLasher_test_year_season_to_timestep_FLQuant_double', PACKAGE = 'FLasher', flq, year, season)
}

test_year_season_to_timestep_FLQuant_adouble <- function(flqad, year, season) {
    .Call('FLasher_test_year_season_to_timestep_FLQuant_adouble', PACKAGE = 'FLasher', flqad, year, season)
}

test_year_season_to_timestep <- function(flq, year, season) {
    .Call('FLasher_test_year_season_to_timestep', PACKAGE = 'FLasher', flq, year, season)
}

test_timestep_to_year_season_FLQuant_double <- function(flq, timestep) {
    .Call('FLasher_test_timestep_to_year_season_FLQuant_double', PACKAGE = 'FLasher', flq, timestep)
}

test_timestep_to_year_season_FLQuant_adouble <- function(flqad, timestep) {
    .Call('FLasher_test_timestep_to_year_season_FLQuant_adouble', PACKAGE = 'FLasher', flqad, timestep)
}

test_timestep_to_year_season <- function(flq, timestep) {
    .Call('FLasher_test_timestep_to_year_season', PACKAGE = 'FLasher', flq, timestep)
}

test_operatingModel_empty_constructor <- function() {
    invisible(.Call('FLasher_test_operatingModel_empty_constructor', PACKAGE = 'FLasher'))
}

test_operatingModel_full_constructor <- function(flfs, flbs_list_sexp, ctrl) {
    .Call('FLasher_test_operatingModel_full_constructor', PACKAGE = 'FLasher', flfs, flbs_list_sexp, ctrl)
}

test_operatingModel_catch_q_adouble <- function(flfs, flbs_list_sexp, ctrl, fishery_no, catch_no, biol_no, indices) {
    .Call('FLasher_test_operatingModel_catch_q_adouble', PACKAGE = 'FLasher', flfs, flbs_list_sexp, ctrl, fishery_no, catch_no, biol_no, indices)
}

test_operatingModel_catch_q_subset <- function(flfs, flbs_list_sexp, ctrl, fishery_no, catch_no, biol_no, indices_min, indices_max) {
    .Call('FLasher_test_operatingModel_catch_q_subset', PACKAGE = 'FLasher', flfs, flbs_list_sexp, ctrl, fishery_no, catch_no, biol_no, indices_min, indices_max)
}

test_operatingModel_catch_q_FLQuantAD <- function(flfs, flbs_list_sexp, ctrl, fishery_no, catch_no, biol_no) {
    .Call('FLasher_test_operatingModel_catch_q_FLQuantAD', PACKAGE = 'FLasher', flfs, flbs_list_sexp, ctrl, fishery_no, catch_no, biol_no)
}

test_operatingModel_get_f <- function(flfs, flbs_list_sexp, ctrl, fishery_no, catch_no, biol_no) {
    .Call('FLasher_test_operatingModel_get_f', PACKAGE = 'FLasher', flfs, flbs_list_sexp, ctrl, fishery_no, catch_no, biol_no)
}

test_operatingModel_get_f_subset <- function(flfs, flbs_list_sexp, ctrl, fishery_no, catch_no, biol_no, indices_min, indices_max) {
    .Call('FLasher_test_operatingModel_get_f_subset', PACKAGE = 'FLasher', flfs, flbs_list_sexp, ctrl, fishery_no, catch_no, biol_no, indices_min, indices_max)
}

test_operatingModel_F_B <- function(flfs, flbs_list_sexp, ctrl, biol_no) {
    .Call('FLasher_test_operatingModel_F_B', PACKAGE = 'FLasher', flfs, flbs_list_sexp, ctrl, biol_no)
}

test_operatingModel_partial_f <- function(flfs, flbs_list_sexp, ctrl, fishery_no, catch_no, biol_no) {
    .Call('FLasher_test_operatingModel_partial_f', PACKAGE = 'FLasher', flfs, flbs_list_sexp, ctrl, fishery_no, catch_no, biol_no)
}

test_operatingModel_partial_f_subset <- function(flfs, flbs_list_sexp, ctrl, fishery_no, catch_no, biol_no, indices_min, indices_max) {
    .Call('FLasher_test_operatingModel_partial_f_subset', PACKAGE = 'FLasher', flfs, flbs_list_sexp, ctrl, fishery_no, catch_no, biol_no, indices_min, indices_max)
}

test_operatingModel_project_timestep <- function(flfs, flbs_list_sexp, ctrl, timestep) {
    .Call('FLasher_test_operatingModel_project_timestep', PACKAGE = 'FLasher', flfs, flbs_list_sexp, ctrl, timestep)
}

test_operatingModel_Z <- function(flfs, flbs_list_sexp, ctrl, biol_no) {
    .Call('FLasher_test_operatingModel_Z', PACKAGE = 'FLasher', flfs, flbs_list_sexp, ctrl, biol_no)
}

test_operatingModel_project <- function(flfs, flbs_list_sexp, ctrl, timestep) {
    .Call('FLasher_test_operatingModel_project', PACKAGE = 'FLasher', flfs, flbs_list_sexp, ctrl, timestep)
}

test_operatingModel_SSB_FLQ <- function(flfs, flbs_list_sexp, ctrl, biol_no) {
    .Call('FLasher_test_operatingModel_SSB_FLQ', PACKAGE = 'FLasher', flfs, flbs_list_sexp, ctrl, biol_no)
}

fwdBiolAD_biomass_subset_speed <- function(fwdb, year, season, rep) {
    invisible(.Call('FLasher_fwdBiolAD_biomass_subset_speed', PACKAGE = 'FLasher', fwdb, year, season, rep))
}

catch_q_speed <- function(flfs, flbs_list_sexp, ctrl, fishery_no, catch_no, biol_no, dim_min, dim_max, rep) {
    invisible(.Call('FLasher_catch_q_speed', PACKAGE = 'FLasher', flfs, flbs_list_sexp, ctrl, fishery_no, catch_no, biol_no, dim_min, dim_max, rep))
}

get_f_speed <- function(flfs, flbs_list_sexp, ctrl, fishery_no, catch_no, biol_no, indices_min, indices_max, rep) {
    invisible(.Call('FLasher_get_f_speed', PACKAGE = 'FLasher', flfs, flbs_list_sexp, ctrl, fishery_no, catch_no, biol_no, indices_min, indices_max, rep))
}

useAuto <- function() {
    .Call('FLasher_useAuto', PACKAGE = 'FLasher')
}

init_list <- function() {
    .Call('FLasher_init_list', PACKAGE = 'FLasher')
}

transformEx2 <- function(x, y) {
    .Call('FLasher_transformEx2', PACKAGE = 'FLasher', x, y)
}

begin_test <- function(init) {
    invisible(.Call('FLasher_begin_test', PACKAGE = 'FLasher', init))
}

