# zzz.R - DESC
# /home/mosquia/Projects/FLR/pkgs/mine/FLasher/R/zzz.R

# Copyright (c) WUR, 2022.
# Author: Iago MOSQUEIRA (WMR) <iago.mosqueira@wur.nl>
#
# Distributed under the terms of the EUPL-1.2


jukebox <- function(){
    tracks <- list(PinkFloyd_VegetableMan = c("In yellow shoes I get the blues", "Though I walk the streets with my plastic feet", "With my blue velvet trousers, make me feel pink", "There's a kind of stink about blue velvet trousers", "In my paisley shirt I look a jerk", "And my turquoise waistcoat is quite out of sight", "But oh oh my haircut looks so bad", "Vegetable man, where are you?", "So I've changed my dear, and I find my knees", "And I covered them up with the latest cut", "And my pants and socks all point in a box", "They don't make long of my nylon socks", "The watch, black watch", "My watch with a black face", "And a big pin, a little hole", "And all the lot is what I got", "It's what I wear, it's what you see", "It must be me, it's what I am", "Vegetable man", "I've been looking all over the place for a place for me", "But it ain't anywhere, it just ain't anywhere", "Vegetable man, vegetable man", "He's the kind of person, you just gonna see him if you can", "Vegetable man"),
                    OM_Gethsemane = c("Sing the advatic - penitent rite to send","Toward redemption - strength attends the seeker", "A sovereign dreadnaught breathes and approach the state serene", "Interiorizer of the mind from world labyrinth", "Nocodemus awaits in vigil weeping", "The Arahat rising and the healing ghost descends", "Lamentations cease enter rarefied light prevails", "Devekut gleams sing freedom from tamasic field", "And Ezekiel saw the wheel", "Prana exits toward the azure locus", "On vrittiless path he walks", "Contemplative ascends", "Temple-cave of the heart shrine", "Vigil on the mountain"),
                    Clutch_BeholdTheColossus = c("Drive us by pitchfork to caves by the sea", "Atop the mountain, under cities", "We are monsters", "We are older than men", "Yes, we are Gorgons", "And we will have our revenge", "Frighten their children by speaking our name", "Epoch and eon, it's always the same", "We are monsters", "But we will no longer run", "We are the Cyclops", "And our time has come", "This world was ours before it had ever known men", "Soon it will be ours again", "Grant them their tales of their forefather's glory", "For soon it will be ours again", "Atop the buttress the gargoyle sits", "The fragile foundation crumbles to bits", "We are monsters and they are but men", "Behold the Colossus rises again!"),
                    OM_StateOfNonReturn = c("Traveler now reach the stream. The astral flight adapter", "From the pain-sheath life ascends - the Non-returner sees", "Empathy release me - and the phoenix rise triumphant", "And walks onto the certitude ground - the soul's submergence ends", "From the rounds of rebirth - he arrives onto the deathless", "Light bores through the adjunct worlds - the soul-galleon prevails", "Liberates in wisdom to complete state of negation", "The five roads subsumed by grace - emancipates from dream"),
                    SatansSatyrs_CurseOfTheCorpse = c("When the unmanned belfry resounds with grim knell", "A fiend returns from halfway to Hell", "With human shape, but demon's gait", "And five grave-bound centuries of hunger to sate", "Do you not remember", "Or do you wish to forget?", "Tonight the corpse will rise", "This night of Walpurgis", "In life he practiced blood-sacrifice", "Left not untapped the blackest vice", "His occult prowess preserved his flesh", "Not among the living nor of the dead", "They say the dead hate the living", "But is it really true?", "You won't guess twice", "When they're coming after you", "You'll find no life behind those eyes", "Don't even risk a glance", "A stake through the heart is not enough", "Don't even stand a chance"),
                    OrangeGoblin_RedTideRising = c("Chaos is calling, the kingdoms are falling", "The planets collide in the sky", "The old ones command, by a curse or by hand", "We've come to the end of our times", "Thoughts paralyzed, a red tide will rise", "Dystopia seen through cephalopod eyes", "Creatures reborn, from weird tales untold", "Visions of horror, dimensions unknown to this world!", "Gods are descending, a force unrelenting", "Cthulhu will rise from the sea", "Turning blood red and awaking the dead", "From their aeons of suffering sleep", "Monoliths rise, to fiery skies", "Empires dead in the shadow of flies", "Serpents unwind, to torture and bind", "No one survives the ultimate fall of mankind!", "Atlantis will rise!", "The Kraken alive!", "These are Fortean times!", "No sanctuary", "No Hail Mary", "No visionary", "Can save you from what has begun!", "Infidels fall to their knees and they start", "Praying to something that's never been there in their hearts", "Searing white light from the guardians flesh", "Azrael rising, wings of the angel of death", "No sanctuary", "No Hail Mary", "No visionary", "Can save you from what has begun!", "This is Leviathan!", "Death of the sun!", "Age of darkness has won"),
                    Cud_PurpleLoveBalloon = c("The first time that I saw you", "You were running scared", "You assured me", "Your clothes were making chase", "Your mouth was making shapes before me", "The second time you touched me", "Your hands sent ripples through me", "You're one in a million, take me home", "Make dragons fly, make dragons roam", "You're one in a million", "And I will see you soon", "I want to take you high in my...", "Purple Love Balloon", "The second time you touched me", "Your hands went running through me", "It was white so I could find me", "The second time you loved me", "The dragon was inside me", "I want to take you high", "In my Purple Love Balloon", "I want to thumb a ride", "In my Purple Love Balloon", "I want to make you fly", "In my Purple Love Balloon"),
                    SuperFurryAnimals_DacwHi = c("Dacw hi, a'I gwyneb mewn poen", "Mae hi newydd gael ei phigo gan byr ar ei chroen", "Mae'n gafael mewn papur cyfagos a'I daro ar y wal", "Mae'n gadael gwennynen ar ?ydd yn sicr wedi ei dal", "Mae hi'n ddoniol", "Mae'n sylwi pob dim", "Ac mae'n medru gweld", "Drwy gefn ei phen", "Dim dioloch I'r drefn", "Mae'n fore iau ac mae'n mynd I'r gwaith", "Wrth gau ei drws mae hi'n tynnu at saith", "Wrth gau ei ch?hag yr oerni mae hi'n colli pishyn punt", "Mae'n ei bigo o fyny yn syth cyn troi n? mewn I'r gwynt", "Mae hi'n ddoniol", "Mae'n sylwi pob dim", "Ac mae'n medru gweld", "Drwy gefn ei phen", "Dim dioloch I'r drefn", "Mae hi'n ddoniol", "Mae'n sylwi pob dim", "Mae hi'n ddoniol", "Neith hi chwerthin ar ddim", "Mae hi'n ddoniol", "Mae'n sylwi pob dim", "Ac mae'n medru gweld", "Drwy gefn ei phen", "Dim dioloch I'r drefn", "Unwaith drachefn", "Amen"),
                    MonsterMagnet_ILiveBehindTheClouds = c("I've got a feeling that no one cares", "'Bout all that confetti I throw in the air", "Nothing's important yet everything is", "If there ain't no photo I just don't exist", "And the winds blow", "And the sky looks cool", "So I make my home in the clouds", "I see the oceans, the mountains, the plains", "The rats and the suckers, the strong and the lame", "Sometimes I dream about flying on down", "Falling in love and life on the ground", "And the winds blow", "And the sun comes up", "And I stay behind the clouds", "Yes I live behind the clouds", "Raise Surya to burn off the soil", "Make it safe for my eyes", "I'd pay good money just to get proved wrong", "For once in my goddamned life", "Pull me in, drag me down", "Into your ocean of love", "My wings are ragged and my soul is gone", "So tired of floating above", "Sing to me baby your sweet refrain", "I feel I'm coming apart in this rain", "That's all I need if that's all I hear", "Some beautiful music as I disappear", "And the winds blow", "And the sun goes down", "And I stay behind the clouds", "Yes I stay behind the clouds", "Yeah I live behind the clouds"))
    trackno <- round(runif(1,min=1,max=length(tracks)))
    lyricno <- round(runif(1,min=1,max=length(tracks[[trackno]])))
    return(tracks[[trackno]][lyricno])
}

.onAttach <- function(libname, pkgname ) {
    startup <- paste("FLasher: ", jukebox(), sep="")
    packageStartupMessage(startup)
}

